--스크랩 삭제
DROP TABLE TB_SCRAP_C;

--챌린지 게시판(삭제)
DROP TABLE TB_BOARD_CHALLENGE;
--CREATE TABLE TB_BOARD_CHALLENGE (
--	POST_NO	NUMBER		NOT NULL,
--	USER_NO	NUMBER		NOT NULL,
--	POST_NAME	VARCHAR2(30)		NOT NULL,
--	POST_CONTENT	VARCHAR2(4000)		NOT NULL,
--	BEG_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
--	CHALLENGE_PERIOD	DATE,
--	PARTI_NUM	NUMBER	DEFAULT '0'	NOT NULL,
--	REVIEW_NUM	NUMBER	DEFAULT '0'	NOT NULL,
--	THUMBNAIL	VARCHAR2(100),
--	MOD_YN	CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
--	FMOD_DATE	TIMESTAMP   DEFAULT SYSDATE,
--	DEL_YN	CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
--    CONSTRAINT PK_TB_BOARD_CHALLENGE PRIMARY KEY(POST_NO),
--    CONSTRAINT FK_TB_BOARD_CHALLENGE FOREIGN KEY(USER_NO) REFERENCES TB_USER(USER_NO)
--);
--
--DROP SEQUENCE SEQ_CHA_PNO;
--CREATE SEQUENCE SEQ_CHA_PNO NOCYCLE NOCACHE;

----새로운 챌린지 게시판 테이블
DROP TABLE TB_POST_C;
CREATE TABLE TB_POST_C (
	POST_NO	NUMBER		NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	POST_NAME	VARCHAR2(30)		NOT NULL,
	POST_CONTENT	VARCHAR2(4000)		NOT NULL,
	BEG_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	CHALLENGE_PERIOD	DATE,
	PARTI_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	REVIEW_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	THUMBNAIL	VARCHAR2(100),
	MOD_YN	CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	FMOD_DATE	TIMESTAMP   DEFAULT SYSDATE,
	DEL_YN	CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_POST_C PRIMARY KEY(POST_NO),
    CONSTRAINT FK_TB_POST_C FOREIGN KEY(USER_NO) REFERENCES TB_USER(USER_NO)
);
DROP SEQUENCE SEQ_CHA_PTO;
CREATE SEQUENCE SEQ_CHA_PTO;

----챌린지 댓글
DROP TABLE TB_COMMENT_C;
CREATE TABLE TB_COMMENT_C (
	COMM_NO	        NUMBER	NOT NULL,
	POST_NO	        NUMBER	NOT NULL,
	USER_NO	        NUMBER	NOT NULL,
	COMM_CONTENT	VARCHAR2(4000)	NOT NULL,
	COMM_ORDER	    NUMBER	NOT NULL,
	RECOM_NUM	    NUMBER	DEFAULT '0' NOT NULL,
	BEG_DATE	    TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MOD_DATE	    TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MOD_YN	        CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	DEL_YN	        CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_COMMENT_C PRIMARY KEY(COMM_NO),
    CONSTRAINT FK_TB_COMMENT_C FOREIGN KEY(POST_NO) REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);
---- 챌린지 대댓글
DROP TABLE TB_COMMENT_C2;
CREATE TABLE TB_COMMENT_C2 (
	COMM_NO NUMBER NOT NULL,
    POST_NO NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
	COMM_CONTENT	VARCHAR2(4000)	NOT NULL,
	COMM_ORDER	NUMBER	    NOT NULL,
	RECOM_NUM	NUMBER	    DEFAULT '0' NOT NULL,
	BEG_DATE	TIMESTAMP   DEFAULT SYSDATE	NOT NULL,
	MOD_DATE	TIMESTAMP	DEFAULT SYSDATE NOT NULL,
	MOD_YN	    CHAR(1)	    DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	DEL_YN	    CHAR(1)	    DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT FK_TB_COMMENT_C2 FOREIGN KEY(COMM_NO) REFERENCES TB_COMMENT_C(COMM_NO),
    FOREIGN KEY (POST_NO) REFERENCES TB_COMMENT_C,
    FOREIGN KEY (USER_NO) REFERENCES TB_COMMENT_C
);

----챌린지 첨부파일
DROP TABLE TB_ATTACHED_FILE_C;
CREATE TABLE TB_ATTACHED_FILE_C (
	FILE_NO	        NUMBER	        NOT NULL,
	POST_NO     	NUMBER	        NOT NULL,
	USER_NO	        NUMBER	        NOT NULL,
	FILE_NAME	    VARCHAR2(255)	DEFAULT '' NOT NULL,
	MFILE_NAME	    VARCHAR2(255)	DEFAULT '' NOT NULL,
    CONSTRAINT PK_TB_ATTACHED_FILE_C PRIMARY KEY(FILE_NO),
    CONSTRAINT FK_TB_ATTACHED_FILE_C FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);

DROP SEQUENCE SEQ_CHA_FNO;
CREATE SEQUENCE SEQ_CHA_FNO NOCYCLE NOCACHE;

----챌린지 리뷰
DROP TABLE TB_REVIEW_C;
CREATE TABLE TB_REVIEW_C(
    REVIEW_NO NUMBER	NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	REVIEW_NAME	VARCHAR2(30)		NOT NULL,
	REVIEW_CONTENT	VARCHAR2(4000)		NOT NULL,
    REVIEW_STAR NUMBER NOT NULL,
	BEG_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
    STAR NUMBER NOT NULL,
	THUMBNAIL	VARCHAR2(100),
	MOD_YN	CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	FMOD_DATE	TIMESTAMP   DEFAULT SYSDATE,
	DEL_YN	CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_REVIEW_C PRIMARY KEY(REVIEW_NO),
    CONSTRAINT FK_TB_REVIEW_C FOREIGN KEY(USER_NO) REFERENCES TB_USER(USER_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);

----챌린지 참여
DROP TABLE TB_PARTICIPATE_C;
CREATE TABLE TB_PARTICIPATE_C (
	PARTI_NO	NUMBER		NOT NULL,
	POST_NO	    NUMBER		NOT NULL,
	USER_NO	    NUMBER		NOT NULL,
	PARTI_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	STOP_YN	CHAR(1)	DEFAULT 'N' CHECK(STOP_YN IN('Y', 'N')),
    USER_NO2    NUMBER	    NOT NULL,
    CONSTRAINT PK_TB_PARTICIPATE_C PRIMARY KEY(PARTI_NO),
    CONSTRAINT FK_TB_PARTICIPATE_C FOREIGN KEY(POST_NO) REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);

ALTER TABLE TB_PARTICIPATE_C ADD CONSTRAINT FK_TB_USER_TO_TB_PARTICIPATE_C FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

DROP SEQUENCE SEQ_CHA_PARNO;
CREATE SEQUENCE SEQ_CHA_PARNO;

----챌린지 댓글 추천
DROP TABLE TB_RECOMMEND_COMMENT_C;
CREATE TABLE TB_RECOMMEND_COMMENT_C (
	RECOM_NO	NUMBER		NOT NULL,
	COMM_NO	    NUMBER		NOT NULL,
	POST_NO	    NUMBER		NOT NULL,
	USER_NO	    NUMBER		NOT NULL,
	RECOM_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	DEL_YN	CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    USER_NO2    NUMBER	    NOT NULL,
    CONSTRAINT PK_TB_RECOMMEND_COMMENT_C PRIMARY KEY(RECOM_NO),
    CONSTRAINT FK_TB_RECOMMEND_COMMENT_C FOREIGN KEY(COMM_NO)
    REFERENCES TB_COMMENT_C(COMM_NO),
    FOREIGN KEY (POST_NO) REFERENCES TB_COMMENT_C,
    FOREIGN KEY (USER_NO) REFERENCES TB_COMMENT_C
);

ALTER TABLE TB_RECOMMEND_COMMENT_C
ADD CONSTRAINT USER_NO2 FOREIGN KEY(USER_NO2) REFERENCES TB_USER(USER_NO);

DROP SEQUENCE SEQ_CHA_RCNO;
CREATE SEQUENCE SEQ_CHA_RCNO;

----챌린지 신고
DROP TABLE CHA_REPORT;
CREATE TABLE CHA_REPORT (
	REPORT_NO	NUMBER		NOT NULL,
	POST_NO	    NUMBER		NOT NULL,
	USER_NO	    NUMBER		NOT NULL,
	REPORT_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	COMM_NO	    NUMBER		NOT NULL,
	USER_NO2	NUMBER		NOT NULL,
    CONSTRAINT PK_CHA_REPORT PRIMARY KEY(REPORT_NO),
    CONSTRAINT FK_CHA_REPORT FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);

ALTER TABLE CHA_REPORT ADD CONSTRAINT FK_TB_USER_TO_CHA_REPORT FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

ALTER TABLE CHA_REPORT ADD CONSTRAINT FK_TB_COMMENT_C_TO_CHA_REPORT FOREIGN KEY (COMM_NO)
REFERENCES TB_COMMENT_C (COMM_NO);

--새로운 챌린지 게시판 테이블에 데이터 넣어
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,1,'일주일 집밥 챌린지','일주일간 집밥 해먹기~ 집에서 밥먹기 아니구여 직접 해먹어야됩니다~ 배달ㄴㄴ',SYSDATE,SYSDATE+30,'100','50','/Recipetory/WebContent/img/challengeBoard/jipbab.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,2,'밀가루 끊기 챌린지','밀가루를 끊으면 피부개선, 다이어트, 소화불량 등에 효과가 있대요~',SYSDATE,SYSDATE+40,'90','30','/Recipetory/WebContent/img/challengeBoard/flour.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,3,'물 2L 마시기 챌린지','세계보건기구 WHO에서는 하루 약 2L 정도의 물을 섭위할 것을 권장하고 있습니다.',SYSDATE,SYSDATE+50,'80','20','/Recipetory/WebContent/img/challengeBoard/water.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,4,'아침먹기 챌린지','활발한 두뇌활동, 식사량 조절, 건강한 체중관리, 원할한 혈당조절을 원하신다면 아침을 먹어보아요~!',SYSDATE,SYSDATE+20,'70','10','/Recipetory/WebContent/img/challengeBoard/breakfast.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,5,'닭가슴살 챌린지','닭가슴살은 노화 방지, 간 기능 개선, 뇌 건강, 혈관이 꺠끗해지는 등 다양한 기능이 있대요. 레시피토리의 다양한 닭가슴살 레시피로 닭가슴살 챌린지에 도전해보아요~!',SYSDATE,SYSDATE+10,'60','5','/Recipetory/WebContent/img/challengeBoard/chickenbreast.jpg','N',NULL,'N');
COMMIT;
