/* 사용자 테이블 */
DROP TABLE TB_USER;
CREATE TABLE TB_USER (
   USER_NO NUMBER NOT NULL,
   USER_ID VARCHAR2(20) NOT NULL,
   USER_PWD VARCHAR2(20) NOT NULL,
   USER_NICKNAME VARCHAR2(20) NOT NULL,
   UESR_EMAIL VARCHAR2(20) NOT NULL,
   USER_PHONE VARCHAR2(20) NOT NULL,
   USER_JOIN_DATE DATE DEFAULT SYSDATE NOT NULL,
   USER_TYPE VARCHAR2(20) NOT NULL,
   USER_DELETE_YN CHAR(1) NOT NULL,
   LASTLOGIN_DATE TIMESTAMP,
   CONSTRAINT PK_TB_USER PRIMARY KEY(USER_NO)
);

/* 챌린지 게시판 테이블 */
DROP TABLE TB_BOARD_CHALLENGE;
CREATE TABLE TB_BOARD_CHALLENGE (
   POST_NO   NUMBER   NOT NULL,
   POST_NAME   VARCHAR2(30)   NOT NULL,
   POST_CONTENT VARCHAR2(30) NOT NULL,
   BEG_DATE   TIMESTAMP   DEFAULT SYSDATE NOT NULL,
   PARTI_NUM   NUMBER  DEFAULT '0' NOT NULL,
   CHALLENGE_PERIOD   TIMESTAMP   NOT NULL,
   SCRAP_NUM   NUMBER   NULL,
   HITS NUMBER DEFAULT '0' NULL,
   COMM_NUM   NUMBER    DEFAULT '0' NULL,
   REVIEW_NUM   NUMBER    DEFAULT '0' NULL,
   REPORT_NUM   NUMBER   NULL,
   THUMBNAIL VARCHAR2(100) NULL,
   MOD_YN   CHAR(1)   DEFAULT 'N' NULL,
   FMOD_DATE   TIMESTAMP   DEFAULT SYSDATE NULL,
   DEL_YN   CHAR(1)   DEFAULT 'N' NULL,
   USER_NO   NUMBER   NOT NULL,
   CONSTRAINT PK_POST_NO PRIMARY KEY(POST_NO),
   CONSTRAINT FK_USER_NO FOREIGN KEY(USER_NO) REFERENCES TB_USER(USER_NO)
);

/* 챌린지 참가 테이블 */
DROP TABLE TB_PARTICIPATE_C;
CREATE TABLE TB_PARTICIPATE_C (
    PARTI_NO NUMBER NOT NULL,
    POST_NO NUMBER NOT NULL,
    PARTI_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
    STOP_YN CHAR(1) DEFAULT 'N' NULL,
    USER_NO NUMBER NOT NULL,
    CONSTRAINT PK_PARTI_NO PRIMARY KEY(PARTI_NO),
    CONSTRAINT FK_CPART_POST_NO FOREIGN KEY(POST_NO) REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    CONSTRAINT FK_CPART_USER_NO FOREIGN KEY(USER_NO) REFERENCES TB_USER(USER_NO)
    );
    
/* 챌린지 댓글 테이블 */
DROP TABLE TB_COMMENT_C;
CREATE TABLE TB_COMMENT_C (
   COMM_NO   NUMBER   NOT NULL,
   POST_NO   NUMBER   NOT NULL,
   COMM_CONTENT   VARCHAR2(4000)   NOT NULL,
   COMM_ORDER   NUMBER   NOT NULL,
   RECOM_NUM   NUMBER   DEFAULT '0' NULL,
   BEG_DATE   TIMESTAMP   DEFAULT SYSDATE NOT NULL,
   MOD_DATE   TIMESTAMP   DEFAULT SYSDATE NULL,
   REPORT_YN   CHAR(1)   DEFAULT 'N' NULL,
   MOD_YN   CHAR(1)   DEFAULT 'N' NULL,
   DEL_YN   CHAR(1)   DEFAULT 'N' NULL,
   USER_NO   NUMBER   NOT NULL,
   CONSTRAINT PK_COMM_NO PRIMARY KEY(COMM_NO),
   CONSTRAINT FK_CCOMM_POST_NO FOREIGN KEY(POST_NO) REFERENCES TB_BOARD_CHALLENGE(POST_NO),
   CONSTRAINT FK_CCOMM_USER_NO FOREIGN KEY(USER_NO) REFERENCES TB_USER(USER_NO)
);

/* 챌린지 추천 테이블 */
DROP TABLE TB_RECOMMEND_COMMENT_C;
CREATE TABLE TB_RECOMMEND_COMMENT_C (
   RECOM_NO   NUMBER   NOT NULL,
   COMM_NO   NUMBER   NOT NULL,
   POST_NO   NUMBER   NOT NULL,
   RECOM_DATE   TIMESTAMP   DEFAULT SYSDATE NOT NULL,
   DEL_YN   CHAR(1)   DEFAULT 'N' NULL,
   USER_NO   NUMBER   NOT NULL,
   CONSTRAINT PK_RECOM_NO PRIMARY KEY(RECOM_NO),
   CONSTRAINT FK_CRECOM_COMM_NO FOREIGN KEY(COMM_NO) REFERENCES TB_COMMENT_C(COMM_NO),
   CONSTRAINT FK_CRECOM_POST_NO FOREIGN KEY(POST_NO) REFERENCES TB_COMMENT_C(POST_NO),
   CONSTRAINT FK_CRECOM_USER_NO FOREIGN KEY(USER_NO) REFERENCES TB_USER(USER_NO)
);

/* 챌린지 대댓글 테이블 */
DROP TABLE TB_COMMENT_C2;
CREATE TABLE TB_COMMENT_C2 (
   COMM_NO   NUMBER   NOT NULL,
   POST_NO   NUMBER   NOT NULL,
   COMM_CONTENT   VARCHAR2(4000)   NOT NULL,
   COMM_ORDER   NUMBER   NOT NULL,
   RECOM_NUM   NUMBER   DEFAULT '0' NULL,
   BEG_DATE   TIMESTAMP DEFAULT SYSDATE NOT NULL,
   MOD_DATE   TIMESTAMP DEFAULT SYSDATE,
   REPORT_YN   CHAR(1)   DEFAULT 'N' NULL,
   MOD_YN   CHAR(1)   DEFAULT 'N' NULL,
   DEL_YN   CHAR(1)   DEFAULT 'N' NULL,
   USER_NO   NUMBER   NOT NULL,
   CONSTRAINT FK_CCOMM2_COMM_NO FOREIGN KEY(COMM_NO) REFERENCES TB_COMMENT_C(COMM_NO),
   CONSTRAINT FK_CCOMM2_POST_NO FOREIGN KEY(POST_NO) REFERENCES TB_COMMENT_C(POST_NO),
   CONSTRAINT FK_CCOMM2_USER_NO FOREIGN KEY(USER_NO) REFERENCES TB_USER(USER_NO)
);

/* 챌린지 스크랩 테이블 */
DROP TABLE TB_SCRAP_C;
CREATE TABLE TB_SCRAP_C(
    SCRAP_NO NUMBER NOT NULL,
    POST_NO NUMBER NOT NULL,
    SCRAP_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
    DEL_YN CHAR(1) DEFAULT 'N' NULL,
    USER_NO NUMBER NOT NULL,
    CONSTRAINT PK_SCRAP_NO PRIMARY KEY(SCRAP_NO),
    CONSTRAINT FK_CSCR_POST_NO FOREIGN KEY(POST_NO) REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    CONSTRAINT FK_CSCR_USER_NO FOREIGN KEY(USER_NO) REFERENCES TB_USER(USER_NO)   
    );
    
/* 챌린지 신고 테이블 */
DROP TABLE TB_REPORT_C;
CREATE TABLE TB_REPORT_C (
	REPORT_NO	NUMBER	NOT NULL,
	POST_NO	NUMBER	NOT NULL,
	COMM_NO	NUMBER	NULL,
	REPORT_DATE	TIMESTAMP DEFAULT SYSDATE NOT NULL,
	USER_NO	NUMBER	NOT NULL,
    CONSTRAINT PK_REPORT_NO PRIMARY KEY(REPORRT_NO),
    CONSTRAINT FK_CREPO_COMM_NO FOREIGN KEY(COMM_NO) REFERENCES TB_COMMENT_C(COMM_NO),
    CONSTRAINT FK_CREPO_POST_NO FOREIGN KEY(POST_NO) REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    CONSTRAINT FK_CREPO_USER_NO FOREIGN KEY(USER_NO) REFERENCES TB_USER(USER_NO)
);

/* 챌린지 첨부파일 테이블 */
DROP TABLE TB_ATTACHED_FILE_C;
CREATE TABLE TB_ATTACHED_FILE_C (
	FILE_NO	NUMBER	NOT NULL,
	POST_NO	NUMBER	NOT NULL,
	USER_NO	NUMBER	NOT NULL,
	FILE_NAME	VARCHAR2	NOT NULL,
	MFILE_NAME	VARCHAR2	NULL,
    CONSTRAINT PK_FILE_NO PRIMARY KEY(FILE_NO),
    CONSTRAINT FK_CATTA_POST_NO FOREIGN KEY(POST_NO) REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    CONSTRAINT FK_CATTA_USER_NO FOREIGN KEY(USER_NO) REFERENCES TB_USER(USER_NO)
);

ALTER TABLE TB_BOARD_RECEIPT RENAME TO TB_BOARD_RECIPE;


--여기서부터~~
--챌린지 게시글 테이블
DROP TABLE TB_BOARD_CHALLENGE;
CREATE TABLE TB_BOARD_CHALLENGE (
	POST_NO	NUMBER		NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	POST_NAME	VARCHAR2(30)		NOT NULL,
	POST_CONTENT	VARCHAR2(4000)		NOT NULL,
	BEG_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	CHALLENGE_PERIOD	TIMESTAMP,
	PARTI_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	HITS	NUMBER	DEFAULT '0'	NOT NULL,
	COMM_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	REVIEW_NUM	NUMBER	DEFAULT '0'	NOT NULL,
    REVIEW_STAR NUMBER NOT NULL,
	THUMBNAIL	VARCHAR2(100),
	MOD_YN	CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	FMOD_DATE	TIMESTAMP   DEFAULT SYSDATE,
	DEL_YN	CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_BOARD_CHALLENGE PRIMARY KEY(POST_NO),
    CONSTRAINT FK_TB_BOARD_CHALLENGE FOREIGN KEY(USER_NO)
    REFERENCES TB_USER(USER_NO)
);

DROP SEQUENCE SEQ_CHA_PNO;
CREATE SEQUENCE SEQ_CHA_PNO;

INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,001,'챌린지 이름','챌린지 게시물 내용',SYSDATE,SYSDATE+20,'0','0','0','0','0','/Recipetory/WebContent/img/challengeBoard/jipbab.jpg','N',NULL,'N');
commit;
DELETE FROM TB_BOARD_CHALLENGE WHERE POST_NAME='챌린지 이름';

INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,001,'일주일 집밥 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+30,'100','5','500','50','40','/Recipetory/WebContent/img/challengeBoard/jipbab.jpg','N',NULL,'N');
INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,002,'밀가루 끊기 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+40,'90','4','400','40','30','/Recipetory/WebContent/img/challengeBoard/flour.jpg','N',NULL,'N');
INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,003,'물 2L 마시기 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+50,'80','3','300','30','20','/Recipetory/WebContent/img/challengeBoard/water.jpg','N',NULL,'N');
INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,004,'아침먹기 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+20,'70','2','200','20','10','/Recipetory/WebContent/img/challengeBoard/breakfast.jpg','N',NULL,'N');
INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,005,'닭가슴살 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+10,'60','1','100','10','5','/Recipetory/WebContent/img/challengeBoard/chickenbreast.jpg','N',NULL,'N');
commit;
select * from TB_BOARD_CHALLENGE;
DELETE FROM TB_BOARD_CHALLENGE WHERE POST_CONTENT='챌린지 게시물 내용';


INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,001,'일주일 집밥 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+30,'100','500','50','40','/img/challengeBoard/jipbab.jpg','N',NULL,'N');
INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,002,'밀가루 끊기 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+40,'90','400','40','30','/img/challengeBoard/flour.jpg','N',NULL,'N');
INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,003,'물 2L 마시기 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+50,'80','300','30','20','/img/challengeBoard/water.jpg','N',NULL,'N');
INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,004,'아침먹기 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+20,'70','200','20','10','/img/challengeBoard/breakfast.jpg','N',NULL,'N');
INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,005,'닭가슴살 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+10,'60','100','10','5','/img/challengeBoard/chickenbreast.jpg','N',NULL,'N');
commit;

ALTER TABLE TB_BOARD_CHALLENGE DROP COLUMN SCRAP_NUM;
INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,001,'일주일 집밥 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+30,'100','5','500','50','40','/img/challengeBoard/jipbab.jpg','N',NULL,'N');
INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,002,'밀가루 끊기 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+40,'90','4','400','40','30','/img/challengeBoard/flour.jpg','N',NULL,'N');
INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,003,'물 2L 마시기 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+50,'80','3','300','30','20','/img/challengeBoard/water.jpg','N',NULL,'N');
INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,004,'아침먹기 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+20,'70','2','200','20','10','/img/challengeBoard/breakfast.jpg','N',NULL,'N');
INSERT INTO TB_BOARD_CHALLENGE VALUES(SEQ_CHA_PNO.NEXTVAL,005,'닭가슴살 챌린지','챌린지 게시물 내용',SYSDATE,SYSDATE+10,'60','1','100','10','5','/img/challengeBoard/chickenbreast.jpg','N',NULL,'N');

CREATE TABLE TB_REVIEW_C
    REVIEW_NO NUMBER	NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	REVIEW_NAME	VARCHAR2(30)		NOT NULL,
	REVIEW_CONTENT	VARCHAR2(4000)		NOT NULL,
    REVIEW_STAR NUMBER NOT NULL,
	BEG_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
    STAR NUMBER NOT NULL,
	HITS	NUMBER	DEFAULT '0'	NOT NULL,
	COMM_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	THUMBNAIL	VARCHAR2(100),
	MOD_YN	CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	FMOD_DATE	TIMESTAMP   DEFAULT SYSDATE,
	DEL_YN	CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_REVIEW_C PRIMARY KEY(POST_NO),
    CONSTRAINT FK_TB_REVIEW_C FOREIGN KEY(USER_NO)
    REFERENCES TB_USER(USER_NO)
);



UPDATE TB_BOARD_CHALLENGE 
SET POST_CONTENT ='일주일간 집밥 해먹기~ 집에서 밥먹기 아니구여 직접 해먹어야됩니다~ 배달ㄴㄴ'
WHERE POST_NAME='일주일 집밥 챌린지';
UPDATE TB_BOARD_CHALLENGE 
SET POST_CONTENT ='밀가루를 끊으면 피부개선, 다이어트, 소화불량 등에 효과가 있대요~'
WHERE POST_NAME='밀가루 끊기 챌린지';
UPDATE TB_BOARD_CHALLENGE 
SET POST_CONTENT ='세계보건기구 WHO에서는 하루 약 2L 정도의 물을 섭위할 것을 권장하고 있습니다.'
WHERE POST_NAME='물 2L 마시기 챌린지';
UPDATE TB_BOARD_CHALLENGE 
SET POST_CONTENT ='활발한 두뇌활동, 식사량 조절, 건강한 체중관리, 원할한 혈당조절을 원하신다면 아침을 먹어보아요~!'
WHERE POST_NAME='아침먹기 챌린지';
UPDATE TB_BOARD_CHALLENGE 
SET POST_CONTENT =
'닭가슴살은 노화 방지, 간 기능 개선, 뇌 건강, 혈관이 꺠끗해지는 등 다양한 기능이 있대요. 레시피토리의 다양한 닭가슴살 레시피로 닭가슴살 챌린지에 도전해보아요~!'
WHERE POST_NAME='닭가슴살 챌린지';
COMMIT;
