------------------------------스크립트 시작.
DROP TABLE MAG_REPORT;
DROP TABLE TB_RECOMMEND_COMMENT_M;
DROP TABLE TB_RECOMMEND_M;
DROP TABLE TB_SCRAP_M;
DROP TABLE TB_ATTACHED_FILE_M;
DROP TABLE TB_COMMENT_M2;
DROP TABLE TB_COMMENT_M;
DROP TABLE TB_BOARD_MAGAZINE;
DROP TABLE TB_ATTACHED_FILE_RP;
DROP TABLE TB_REPORT;
DROP TABLE TB_ATTACHED_FILE_Q;
DROP TABLE TB_QNA;
DROP TABLE TB_ATTACHED_FILE_N;
DROP TABLE TB_NOTICE;
DROP TABLE TB_ADMIN;
DROP TABLE TB_USER;
DROP TABLE TB_BOARD_CHALLENGE;
DROP TABLE TB_COMMENT_C;
DROP TABLE TB_COMMENT_C2;
DROP TABLE TB_ATTACHED_FILE_C;
DROP TABLE TB_SCRAP_C;
DROP TABLE TB_PARTICIPATE_C;
DROP TABLE TB_RECOMMEND_COMMENT_C;
DROP TABLE CHA_REPORT;
DROP TABLE TB_BOARD_RECEIPT;
DROP TABLE TB_BOARD_RECIPE;
DROP TABLE TB_COMMNET_R;
DROP TABLE TB_COMMENT_R2;
DROP TABLE TB_ATTACHED_FILE_R;
DROP TABLE TB_SCRAP_R;
DROP TABLE TB_RECOMMEND_R;
DROP TABLE TB_RECOMMEND_COMMENT_R;
DROP TABLE REC_REPORT;

DROP SEQUENCE SEQ_MAG_RCNO;
DROP SEQUENCE SEQ_MAG_RNO;
DROP SEQUENCE SEQ_MAG_SNO;
DROP SEQUENCE SEQ_MAG_FNO;
DROP SEQUENCE SEQ_MAG_CNO;
DROP SEQUENCE SEQ_MAG_PNO;
DROP SEQUENCE SEQ_REPORT;
DROP SEQUENCE SEQ_QNA;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_ADMIN;
DROP SEQUENCE SEQ_UNO;

COMMIT;

-------------------------------회원 테이블 생성
DROP TABLE TB_USER;
CREATE TABLE TB_USER (
   USER_NO NUMBER NOT NULL,
   USER_ID VARCHAR2(30) NOT NULL,
   USER_PWD VARCHAR2(100) NOT NULL,
   USER_NICKNAME VARCHAR2(30) NOT NULL,
   USER_EMAIL VARCHAR2(100) NOT NULL,
   USER_PHONE VARCHAR2(13) NOT NULL,
   USER_JOIN_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
   USER_TYPE CHAR(1) DEFAULT 'G' NOT NULL,
   USER_DELETE_YN VARCHAR2(1) DEFAULT 'N' CHECK(USER_DELETE_YN IN('Y', 'N')), --CHECK(컬럼명 IN('Y' , 'N'))은 둘중 하나만 들어갈수 있다는 것.
   LASTLOGIN_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
   CONSTRAINT PK_TB_USER PRIMARY KEY(USER_NO),
   CONSTRAINT CHK_USER_DELETE_YN CHECK (USER_DELETE_YN IN ('Y','N'))
)
;

--회원 코멘트 생성
COMMENT ON COLUMN TB_USER.USER_NO IS '회원 번호';
COMMENT ON COLUMN TB_USER.USER_ID IS '아이디';
COMMENT ON COLUMN TB_USER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN TB_USER.USER_NICKNAME IS '닉네임';
COMMENT ON COLUMN TB_USER.USER_EMAIL IS '이메일';
COMMENT ON COLUMN TB_USER.USER_PHONE IS '전화번호';
COMMENT ON COLUMN TB_USER.USER_JOIN_DATE IS '가입 일자';
COMMENT ON COLUMN TB_USER.USER_TYPE IS '회원 구분 G/Y';
COMMENT ON COLUMN TB_USER.USER_DELETE_YN IS '탈퇴 여부';
COMMENT ON COLUMN TB_USER.LASTLOGIN_DATE IS '마지막 로그인 일자';

DROP SEQUENCE SEQ_UNO;
CREATE SEQUENCE SEQ_UNO; --회원번호 PK값 만들어주기 위한 시퀀스.(회원가입 하면서 번호 붙여지게)

INSERT INTO TB_USER ( --관리자 계정 추가. admin ssh
    USER_NO,
    USER_ID,
    USER_PWD,
    USER_NICKNAME,
    USER_EMAIL,
    USER_PHONE,
    USER_JOIN_DATE,
    USER_TYPE,
    USER_DELETE_YN,
    LASTLOGIN_DATE
    ) VALUES(
    SEQ_UNO.NEXTVAL,
    'admin_ssh',
    'admin_ssh',
    '관리자 서성환',
    'thespeace1@gmail.com',
    '010-2015-9465',
    default,
    default,
    default,
    default
    );
    
    
INSERT INTO TB_USER(
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'red',  '111',  '빨강이', 'red@gmail.com', '010-1111-1111', DEFAULT, DEFAULT, DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'orange',  '222',  '주황이', 'orange@gmail.com', '010-2222-2222',  DEFAULT, DEFAULT, DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'yellow',  '333',  '노랑이', 'yellow@gmail.com', '010-3333-3333', DEFAULT, DEFAULT, DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'green',  '444',  '초록이', 'green@gmail.com', '010-4444-4444', DEFAULT, DEFAULT, DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'blue',  '555',  '파랑이', 'blue@gmail.com', '010-5555-5555', DEFAULT, DEFAULT, DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'navy',  '666',  '남이', 'navy@gmail.com', '010-6666-6666', DEFAULT, DEFAULT, DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'purple',  '777',  '보라', 'purple@gmail.com', '010-7777-7777', DEFAULT, DEFAULT, DEFAULT, DEFAULT );



--------------------------------관리자 테이블 생성
DROP TABLE TB_ADMIN;
CREATE TABLE TB_ADMIN (
   ADMIN_NO NUMBER NOT NULL,
   ADMIN_ID VARCHAR2(30) NOT NULL,
   ADMIN_PWD VARCHAR2(100) NOT NULL,
   ADMIN_NAME VARCHAR2(30) NOT NULL,
   ADMIN_LV VARCHAR2(30) DEFAULT 'Lv1' NOT NULL,
   JOIN_DATE TIMESTAMP DEFAULT SYSDATE,
   DELETE_DATE TIMESTAMP,
   CONSTRAINT PK_TB_ADMIN PRIMARY KEY(ADMIN_NO)
);

DROP SEQUENCE SEQ_ADMIN;
CREATE SEQUENCE SEQ_ADMIN;

--관리자 테이블에 값 입력
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE, DELETE_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin1',  'aaa',  '강동원', DEFAULT, DEFAULT, DEFAULT );
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE, DELETE_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin2',  'bbb',  '이지은', 'Lv3', DEFAULT, DEFAULT );
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE, DELETE_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin3',  'ccc',  '최우식', 'Lv2', DEFAULT, DEFAULT );
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE, DELETE_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin4',  'ddd',  '제임스', 'Lv2', DEFAULT, DEFAULT );
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE, DELETE_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin5',  'eee',  '찰스', DEFAULT, DEFAULT, DEFAULT );


--------------------------------------------------------------------
--공지사항 테이블 생성
DROP TABLE TB_NOTICE;
CREATE TABLE TB_NOTICE (
   NOTICE_NO NUMBER NOT NULL,
   ADMIN_NO NUMBER NOT NULL,
   NOTICE_TITLE VARCHAR2(255) NOT NULL,
   NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
   CREATE_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
   HITS NUMBER DEFAULT '0' NOT NULL,
   MOD_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(MOD_YN IN('Y', 'N')),
   MOD_DATE  TIMESTAMP DEFAULT SYSDATE,
   DELETE_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(DELETE_YN IN('Y', 'N')),
   CONSTRAINT PK_TB_NOTICE PRIMARY KEY(NOTICE_NO),
   CONSTRAINT FK_TB_NOTICE FOREIGN KEY(ADMIN_NO)
   REFERENCES TB_ADMIN(ADMIN_NO)
);

DROP SEQUENCE SEQ_NOTICE;
CREATE SEQUENCE SEQ_NOTICE;

--공지사항 테이블에 값 입력
INSERT INTO TB_NOTICE (
	NOTICE_NO, ADMIN_NO, NOTICE_TITLE,  NOTICE_CONTENT, CREATE_DATE, HITS, MOD_YN, MOD_DATE, DELETE_YN
	) VALUES (
	SEQ_NOTICE.NEXTVAL, '1', '레시피토리 오픈 안내',  '공지사항 내용',  DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
	NOTICE_NO, ADMIN_NO, NOTICE_TITLE,  NOTICE_CONTENT,  CREATE_DATE, HITS,  MOD_YN, MOD_DATE, DELETE_YN
	) VALUES (
	SEQ_NOTICE.NEXTVAL,  '2', '서비스 이용약관 개정 안내',  '공지사항 내용', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
	NOTICE_NO, ADMIN_NO, NOTICE_TITLE,  NOTICE_CONTENT,  CREATE_DATE, HITS,  MOD_YN, MOD_DATE, DELETE_YN
	) VALUES (
	SEQ_NOTICE.NEXTVAL, '3', '서비스 개편 및 이용안내',  '공지사항 내용', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
	NOTICE_NO, ADMIN_NO, NOTICE_TITLE,  NOTICE_CONTENT,  CREATE_DATE, HITS,  MOD_YN, MOD_DATE, DELETE_YN
	) VALUES (
	SEQ_NOTICE.NEXTVAL, '4', '업그레이드 안내 공지',  '공지사항 내용',  DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
    
--공지사항 첨부파일 테이블 생성
DROP TABLE TB_ATTACHED_FILE_N;
CREATE TABLE TB_ATTACHED_FILE_N (
	FILE_NO NUMBER NOT NULL,
    NOTICE_NO NUMBER NOT NULL,
    ADMIN_NO NUMBER NOT NULL,
	FILE_NAME VARCHAR2(255) NOT NULL,
	MFILE_NAME VARCHAR2(255) NOT NULL,
	CONSTRAINT PK_TB_ATTACHED_FILE_N PRIMARY KEY(FILE_NO),
	CONSTRAINT FK_TB_ATTACHED_FILE_N FOREIGN KEY(NOTICE_NO)
    REFERENCES TB_NOTICE(NOTICE_NO),
    FOREIGN KEY (ADMIN_NO) REFERENCES TB_NOTICE
);

--------------------------------------------------------------------------------

--고객 문의사항 테이블 생성
DROP TABLE TB_QNA;
CREATE TABLE TB_QNA (
   QNA_NO NUMBER NOT NULL,
   QNA_TITLE VARCHAR2(255) NOT NULL,
   QNA_CONTENT VARCHAR2(4000) NOT NULL,
   USER_NO NUMBER NOT NULL,
   ADMIN_NO NUMBER,
   CREATE_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
   HITS NUMBER DEFAULT '0' NOT NULL,
   ANSWER VARCHAR2(4000),
   MOD_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(MOD_YN IN('Y', 'N')),
   MOD_DATE  TIMESTAMP DEFAULT SYSDATE,
   STATUS_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(STATUS_YN IN('Y', 'N')),
   DELETE_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(DELETE_YN IN('Y', 'N'))
);
ALTER TABLE TB_QNA ADD CONSTRAINT PK_TB_QNA PRIMARY KEY (QNA_NO,USER_NO);
ALTER TABLE TB_QNA ADD CONSTRAINT FK_TB_USER_TO_TB_QNA_1 FOREIGN KEY (USER_NO)
REFERENCES TB_USER (USER_NO);

ALTER TABLE TB_QNA ADD CONSTRAINT FK_TB_ADMIN_TO_TB_QNA FOREIGN KEY (ADMIN_NO)
REFERENCES TB_ADMIN (ADMIN_NO);

DROP SEQUENCE SEQ_QNA;
CREATE SEQUENCE SEQ_QNA;


--문의사항 테이블에 값 입력
INSERT INTO TB_QNA (
	QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, ADMIN_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_QNA.NEXTVAL, '회원가입 문의',  '문의사항 내용', '1', '1',  DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_QNA (
	QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, ADMIN_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_QNA.NEXTVAL, '레시피 올리는 방법',  '문의사항 내용', '4', '1', DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_QNA (
	QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, ADMIN_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_QNA.NEXTVAL, '비밀번호 변경',  '문의사항 내용', '3', '3', DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_QNA (
	QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, ADMIN_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_QNA.NEXTVAL, '레시피 수정',  '문의사항 내용', '2', '2', DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_QNA (
	QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, ADMIN_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_QNA.NEXTVAL,'동영상 첨부 방법 문의',  '문의사항 내용', '1', '1', DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);

--문의사항 첨부파일 테이블 생성
DROP TABLE TB_ATTACHED_FILE_Q;
CREATE TABLE TB_ATTACHED_FILE_Q (
	FILE_NO	NUMBER		NOT NULL,
	QNA_NO	NUMBER		NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	FILE_NAME	VARCHAR2(255)		NOT NULL,
	MFILE_NAME	VARCHAR2(255)		NOT NULL,
    CONSTRAINT PK_TB_ATTACHED_FILE_Q PRIMARY KEY(FILE_NO),
    CONSTRAINT FK_TB_ATTACHED_FILE_Q FOREIGN KEY(QNA_NO)
    REFERENCES TB_QNA(QNA_NO),
); --왜안만들어져 씨발


--신고 테이블 생성
DROP TABLE TB_REPORT;
CREATE TABLE TB_REPORT (
   REPORT_NO NUMBER NOT NULL,
   REPORT_TITLE VARCHAR2(255) NOT NULL,
   REPORT_CONTENT VARCHAR2(4000) NOT NULL,
   CREATE_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
   HITS NUMBER DEFAULT '0' NOT NULL,
   ANSWER VARCHAR2(4000),
   MOD_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(MOD_YN IN('Y', 'N')),
   MOD_DATE  TIMESTAMP DEFAULT SYSDATE,
   STATUS_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(STATUS_YN IN('Y', 'N')),
   DELETE_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(DELETE_YN IN('Y', 'N')),
   ADMIN_NO NUMBER,
   CONSTRAINT PK_TB_REPORT PRIMARY KEY(REPORT_NO),
   CONSTRAINT FK_TB_REPORT_ADMIN FOREIGN KEY (ADMIN_NO) REFERENCES TB_ADMIN(ADMIN_NO)
);

DROP SEQUENCE SEQ_REPORT;
CREATE SEQUENCE SEQ_REPORT;
--모든 게시글 신고 시퀀스로 사용 SEQ_REPORT

--신고 테이블에 값 입력
INSERT INTO TB_REPORT (
	REPORT_NO, REPORT_TITLE, REPORT_CONTENT, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN, ADMIN_NO
	) VALUES (
	SEQ_REPORT.NEXTVAL,'게시글 신고',  '신고 내용',  DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT, '1');
    
    

—신고 첨부파일 테이블 생성
DROP TABLE TB_ATTACHED_FILE_RP;
CREATE TABLE TB_ATTACHED_FILE_RP (
	FILE_NO NUMBER NOT NULL,
	FILE_NAME VARCHAR2(255) NOT NULL,
	MFILE_NAME VARCHAR2(255) NOT NULL,
    REPORT_NO NUMBER NOT NULL,
	CONSTRAINT PK_ATTACHED_RP PRIMARY KEY(FILE_NO),
    CONSTRAINT FK_TB_ATTACHED_FILE_RP FOREIGN KEY(REPORT_NO)
    REFERENCES TB_REPORT(REPORT_NO)
);

------------------------------------------매거진---------------------------------------------------
--매거진 게시글 테이블 생성
DROP TABLE TB_BOARD_MAGAZINE;
CREATE TABLE TB_BOARD_MAGAZINE (
	POST_NO	        NUMBER                  NOT NULL,
	USER_NO	        NUMBER	                NOT NULL,
	POST_NAME	    VARCHAR2(255)           NOT NULL,
	POST_CONTENT	VARCHAR2(4000)          NOT NULL,
	BEG_DATE	    TIMESTAMP DEFAULT SYSDATE	NOT NULL,
	HITS	        NUMBER  DEFAULT '0' 	NOT NULL,
	RECOM_NUM   	NUMBER	DEFAULT '0'     NOT NULL,
	SCRAP_NUM	    NUMBER	DEFAULT '0'     NOT NULL,
	COMM_NUM	    NUMBER	DEFAULT '0'     NOT NULL,
	MOD_YN	        CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	FMOD_DATE   	TIMESTAMP DEFAULT SYSDATE NOT NULL,
	DEL_YN	        CHAR(1) DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_BOARD_MAGAZINE PRIMARY KEY(POST_NO),
    CONSTRAINT FK_TB_BOARD_MAGAZINE FOREIGN KEY(USER_NO)
    REFERENCES TB_USER(USER_NO)
)
;



--매거진 게시글 코멘트 생성
COMMENT ON COLUMN TB_BOARD_MAGAZINE.POST_NO IS '매거진 게시글 번호';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.USER_NO IS '회원 번호';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.POST_NAME IS '매거진명';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.POST_CONTENT IS '매거진 본문 내용';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.BEG_DATE IS '작성일';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.HITS IS '조회 수';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.RECOM_NUM IS '추천 수';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.SCRAP_NUM IS '스크랩 수';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.COMM_NUM IS '댓글 수';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.MOD_YN IS '수정 여부';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.FMOD_DATE IS '마지막 수정일자';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.DEL_YN IS '삭제 여부';

DROP SEQUENCE SEQ_MAG_PNO;
CREATE SEQUENCE SEQ_MAG_PNO;



-------------------------------------매거진 댓글
DROP TABLE TB_COMMENT_M;
CREATE TABLE TB_COMMENT_M (
	COMM_NO	        NUMBER	NOT NULL,
	POST_NO	        NUMBER	NOT NULL,
	USER_NO	        NUMBER	NOT NULL,
	COMM_CONTENT	VARCHAR2(4000)	NOT NULL,
	COMM_ORDER	    NUMBER	NOT NULL,
	RECOM_NUM	    NUMBER	DEFAULT '0' NOT NULL,
	BEG_DATE	    TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MOD_DATE	    TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MOD_YN	        CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	DEL_YN	        CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_COMMENT_M PRIMARY KEY(COMM_NO),
    CONSTRAINT FK_TB_COMMENT_M FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_MAGAZINE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_MAGAZINE
);

--매거진 댓글 코멘트
COMMENT ON COLUMN TB_COMMENT_M.COMM_NO IS '댓글번호';
COMMENT ON COLUMN TB_COMMENT_M.POST_NO IS '메거진 게시글번호';
COMMENT ON COLUMN TB_COMMENT_M.USER_NO IS '회원번호';
COMMENT ON COLUMN TB_COMMENT_M.COMM_CONTENT IS '댓글내용';
COMMENT ON COLUMN TB_COMMENT_M.COMM_ORDER IS '댓글순서';
COMMENT ON COLUMN TB_COMMENT_M.RECOM_NUM IS '추천수';
COMMENT ON COLUMN TB_COMMENT_M.BEG_DATE IS '작성일';
COMMENT ON COLUMN TB_COMMENT_M.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_COMMENT_M.MOD_YN IS '수정여부';
COMMENT ON COLUMN TB_COMMENT_M.DEL_YN IS '삭제여부';

DROP SEQUENCE SEQ_MAG_CNO;
CREATE SEQUENCE SEQ_MAG_CNO;
DROP SEQUENCE SEQ_MAG_CNO_CNO;
CREATE SEQUENCE SEQ_MAG_CNO_CNO;


-------------------------------------메거진 대댓글
DROP TABLE TB_COMMENT_M2;
CREATE TABLE TB_COMMENT_M2 (
    COMM_NO NUMBER NOT NULL,
    POST_NO NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
	COMM_CONTENT	VARCHAR2(4000)	NOT NULL,
	COMM_ORDER	NUMBER	    NOT NULL,
	RECOM_NUM	NUMBER	    DEFAULT '0' NOT NULL,
	BEG_DATE	TIMESTAMP   DEFAULT SYSDATE	NOT NULL,
	MOD_DATE	TIMESTAMP	DEFAULT SYSDATE NOT NULL,
	MOD_YN	    CHAR(1)	    DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	DEL_YN	    CHAR(1)	    DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT FK_TB_COMMENT_M2 FOREIGN KEY(COMM_NO)
    REFERENCES TB_COMMENT_M(COMM_NO),
    FOREIGN KEY (POST_NO) REFERENCES TB_COMMENT_M,
    FOREIGN KEY (USER_NO) REFERENCES TB_COMMENT_M
);

--매거진 대댓글 코멘트
COMMENT ON COLUMN TB_COMMENT_M2.COMM_NO IS '댓글번호';
COMMENT ON COLUMN TB_COMMENT_M2.POST_NO IS '메거진 게시글번호';
COMMENT ON COLUMN TB_COMMENT_M2.USER_NO IS '회원번호';
COMMENT ON COLUMN TB_COMMENT_M2.COMM_CONTENT IS '댓글내용';
COMMENT ON COLUMN TB_COMMENT_M2.COMM_ORDER IS '댓글순서';
COMMENT ON COLUMN TB_COMMENT_M2.RECOM_NUM IS '추천수';
COMMENT ON COLUMN TB_COMMENT_M2.BEG_DATE IS '작성일';
COMMENT ON COLUMN TB_COMMENT_M2.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_COMMENT_M2.MOD_YN IS '수정여부';
COMMENT ON COLUMN TB_COMMENT_M2.DEL_YN IS '삭제여부';


--매거진 첨부파일관리 테이블 생성
DROP TABLE TB_ATTACHED_FILE_M;
CREATE TABLE TB_ATTACHED_FILE_M (
	FILE_NO	        NUMBER	        NOT NULL,
	POST_NO     	NUMBER	        NOT NULL,
	USER_NO	        NUMBER	        NOT NULL,
	FILE_NAME	    VARCHAR2(255)	DEFAULT '' NOT NULL,
	MFILE_NAME	    VARCHAR2(255)	DEFAULT '' NOT NULL,
    CONSTRAINT PK_TB_ATTACHED_FILE_M PRIMARY KEY(FILE_NO),
    CONSTRAINT FK_TB_ATTACHED_FILE_M FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_MAGAZINE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_MAGAZINE
)
;

--매거진 첨부파일 코멘트
COMMENT ON COLUMN TB_ATTACHED_FILE_M.FILE_NO IS '파일번호';
COMMENT ON COLUMN TB_ATTACHED_FILE_M.POST_NO IS '메거진 게시글번호';
COMMENT ON COLUMN TB_ATTACHED_FILE_M.USER_NO IS '회원번호';
COMMENT ON COLUMN TB_ATTACHED_FILE_M.FILE_NAME IS '파일명';
COMMENT ON COLUMN TB_ATTACHED_FILE_M.MFILE_NAME IS '업로드 후 파일명';

--매거진 첨부파일번호 시퀀스
DROP SEQUENCE SEQ_MAG_FNO;
CREATE SEQUENCE SEQ_MAG_FNO;


------------------------매거진 스크랩
DROP TABLE TB_SCRAP_M;

CREATE TABLE TB_SCRAP_M (
	SCRAP_NO	    NUMBER	    NOT NULL,
	USER_NO	        NUMBER	    NOT NULL,
	POST_NO	        NUMBER	    NOT NULL,
	USER_NO2     	NUMBER	    NOT NULL,
	SCARP_DATE	    TIMESTAMP	DEFAULT SYSDATE NOT NULL,
	DEL_YN	        CHAR(1)	    DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_SCRAP_M PRIMARY KEY(SCRAP_NO),
    CONSTRAINT FK_TB_SCRAP_M FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_MAGAZINE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_MAGAZINE
);

ALTER TABLE TB_SCRAP_M ADD CONSTRAINT FK_TB_USER_TO_TB_SCRAP_M_1 FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

--메거진 스크랩 코멘트
COMMENT ON COLUMN TB_SCRAP_M.SCRAP_NO IS '스크랩번호';
COMMENT ON COLUMN TB_SCRAP_M.USER_NO IS '스크랩한 게시물 작성 회원번호';
COMMENT ON COLUMN TB_SCRAP_M.POST_NO IS '매거진글번호';
COMMENT ON COLUMN TB_SCRAP_M.USER_NO2 IS '스크랩한 회원 번호';
COMMENT ON COLUMN TB_SCRAP_M.SCARP_DATE IS '스크랩일';
COMMENT ON COLUMN TB_SCRAP_M.DEL_YN IS '삭제여부';

--매거진 스크랩 시퀀스
DROP SEQUENCE SEQ_MAG_SNO;
CREATE SEQUENCE SEQ_MAG_SNO;


---------------------매거진 게시글 추천
DROP TABLE TB_RECOMMEND_M;
CREATE TABLE TB_RECOMMEND_M (
	RECOM_NO	    NUMBER		NOT NULL,
	POST_NO	        NUMBER		NOT NULL,
	USER_NO	        NUMBER		NOT NULL,
	RECOM_DATE	    TIMESTAMP   DEFAULT SYSDATE NOT NULL,
	DEL_YN	        CHAR(1)	    DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
	USER_NO2	    NUMBER		NOT NULL,
    CONSTRAINT PK_TB_RECOMMEND_M PRIMARY KEY(RECOM_NO),
    CONSTRAINT FK_TB_RECOMMEND_M FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_MAGAZINE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_MAGAZINE
);

ALTER TABLE TB_RECOMMEND_M ADD CONSTRAINT FK_TB_USER_TO_TB_RECOMMEND_M FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

--메거진 게시글 추천 코멘트
COMMENT ON COLUMN TB_RECOMMEND_M.RECOM_NO IS '추천번호';
COMMENT ON COLUMN TB_RECOMMEND_M.POST_NO IS '매거진 게시글번호';
COMMENT ON COLUMN TB_RECOMMEND_M.USER_NO IS '추천 당한 회원번호';
COMMENT ON COLUMN TB_RECOMMEND_M.RECOM_DATE IS '추천일';
COMMENT ON COLUMN TB_RECOMMEND_M.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_RECOMMEND_M.USER_NO2 IS '추천한 회원번호';

--매거진 게시글 추천 시퀀스
DROP SEQUENCE SEQ_MAG_RNO;
CREATE SEQUENCE SEQ_MAG_RNO;


---------------------------------메거진 댓글 추천
DROP TABLE TB_RECOMMEND_COMMENT_M;

CREATE TABLE TB_RECOMMEND_COMMENT_M (
	RECOM_NO	NUMBER		NOT NULL,
	COMM_NO	    NUMBER		NOT NULL,
	POST_NO	    NUMBER		NOT NULL,
	USER_NO	    NUMBER		NOT NULL,
	RECOM_DATE	TIMESTAMP   DEFAULT SYSDATE NOT NULL,
	DEL_YN	    CHAR(1)	    DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
	USER_NO2	NUMBER		NOT NULL,
    CONSTRAINT PK_TB_RECOMMEND_COMMENT_M PRIMARY KEY(RECOM_NO),
    CONSTRAINT FK_TB_RECOMMEND_COMMENT_M FOREIGN KEY(COMM_NO)
    REFERENCES TB_COMMENT_M(COMM_NO),
    FOREIGN KEY (POST_NO) REFERENCES TB_COMMENT_M,
    FOREIGN KEY (USER_NO) REFERENCES TB_COMMENT_M
);

ALTER TABLE TB_RECOMMEND_COMMENT_M
ADD CONSTRAINT USER_NO2 FOREIGN KEY(USER_NO2) REFERENCES TB_USER(USER_NO);

--메거진 게시글 댓글 추천 코멘트
COMMENT ON COLUMN TB_RECOMMEND_COMMENT_M.RECOM_NO IS '추천번호';
COMMENT ON COLUMN TB_RECOMMEND_COMMENT_M.COMM_NO IS '댓글번호';
COMMENT ON COLUMN TB_RECOMMEND_COMMENT_M.POST_NO IS '매거진 게시글번호';
COMMENT ON COLUMN TB_RECOMMEND_COMMENT_M.USER_NO IS '추천 당한 회원번호';
COMMENT ON COLUMN TB_RECOMMEND_COMMENT_M.RECOM_DATE IS '추천일';
COMMENT ON COLUMN TB_RECOMMEND_COMMENT_M.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_RECOMMEND_COMMENT_M.USER_NO2 IS '추천한 회원번호';

--매거진 게시글 댓글 추천 시퀀스
DROP SEQUENCE SEQ_MAG_RCNO;
CREATE SEQUENCE SEQ_MAG_RCNO;


------------------------------------매거진 신고관리 테이블
DROP TABLE MAG_REPORT;

CREATE TABLE MAG_REPORT (
	REPORT_NO	NUMBER		NOT NULL,
	POST_NO	    NUMBER		NOT NULL,
	COMM_NO	    NUMBER,
	USER_NO2	NUMBER		NOT NULL,
	REPORT_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	USER_NO	    NUMBER		NOT NULL,
    CONSTRAINT PK_MAG_REPORT PRIMARY KEY(REPORT_NO),
    CONSTRAINT FK_MAG_REPORT FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_MAGAZINE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_MAGAZINE
);

ALTER TABLE MAG_REPORT ADD CONSTRAINT FK_TB_USER_TO_MAG_REPORT FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

ALTER TABLE MAG_REPORT ADD CONSTRAINT FK_TB_COMMENT_M_TO_MAG_REPORT FOREIGN KEY (COMM_NO)
REFERENCES TB_COMMENT_M (COMM_NO);

--매거진 신고관리 코멘트
COMMENT ON COLUMN MAG_REPORT.REPORT_NO IS '신고접수번호';
COMMENT ON COLUMN MAG_REPORT.POST_NO IS '매거진글번호';
COMMENT ON COLUMN MAG_REPORT.USER_NO IS '신고 당한 회원번호';
COMMENT ON COLUMN MAG_REPORT.REPORT_DATE IS '접수일';
COMMENT ON COLUMN MAG_REPORT.USER_NO2 IS '신고한 회원번호';
COMMENT ON COLUMN MAG_REPORT.COMM_NO IS '댓글번호';

--매거진 신고관리 시퀀스
--SEQ_REPORT



---------------------------------챌린지---------------------------------
--챌린지 게시글 테이블
DROP TABLE TB_BOARD_CHALLENGE;
CREATE TABLE TB_BOARD_CHALLENGE (
	POST_NO	NUMBER		NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	POST_NAME	VARCHAR2(30)		NOT NULL,
	POST_CONTENT	VARCHAR2(4000)		NOT NULL,
	BEG_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	CHALLENGE_PERIOD	TIMESTAMP,
	PARTI_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	SCRAP_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	HITS	NUMBER	DEFAULT '0'	NOT NULL,
	COMM_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	REVIEW_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	THUMBNAIL	VARCHAR2(100),
	MOD_YN	CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	FMOD_DATE	TIMESTAMP   DEFAULT SYSDATE,
	DEL_YN	CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_BOARD_CHALLENGE PRIMARY KEY(POST_NO),
    CONSTRAINT FK_TB_BOARD_CHALLENGE FOREIGN KEY(USER_NO)
    REFERENCES TB_USER(USER_NO)
);

DROP SEQUENCE SEQ_CHA_PNO;
CREATE SEQUENCE SEQ_CHA_PNO;

--챌린지 댓글 테이블 생성
DROP TABLE TB_COMMENT_C;
CREATE TABLE TB_COMMENT_C (
	COMM_NO	        NUMBER	NOT NULL,
	POST_NO	        NUMBER	NOT NULL,
	USER_NO	        NUMBER	NOT NULL,
	COMM_CONTENT	VARCHAR2(4000)	NOT NULL,
	COMM_ORDER	    NUMBER	NOT NULL,
	RECOM_NUM	    NUMBER	DEFAULT '0' NOT NULL,
	BEG_DATE	    TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MOD_DATE	    TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MOD_YN	        CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	DEL_YN	        CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_COMMENT_C PRIMARY KEY(COMM_NO),
    CONSTRAINT FK_TB_COMMENT_C FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);

DROP SEQUENCE SEQ_CHA_CNO;
CREATE SEQUENCE SEQ_CHA_CNO;

--챌린지 대댓글 테이블 생성
DROP TABLE TB_COMMENT_C2;
CREATE TABLE TB_COMMENT_C2 (
	COMM_NO NUMBER NOT NULL,
    POST_NO NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
	COMM_CONTENT	VARCHAR2(4000)	NOT NULL,
	COMM_ORDER	NUMBER	    NOT NULL,
	RECOM_NUM	NUMBER	    DEFAULT '0' NOT NULL,
	BEG_DATE	TIMESTAMP   DEFAULT SYSDATE	NOT NULL,
	MOD_DATE	TIMESTAMP	DEFAULT SYSDATE NOT NULL,
	MOD_YN	    CHAR(1)	    DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	DEL_YN	    CHAR(1)	    DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT FK_TB_COMMENT_C2 FOREIGN KEY(COMM_NO)
    REFERENCES TB_COMMENT_C(COMM_NO),
    FOREIGN KEY (POST_NO) REFERENCES TB_COMMENT_C,
    FOREIGN KEY (USER_NO) REFERENCES TB_COMMENT_C
);

--챌린지 첨부파일 테이블 생성
DROP TABLE TB_ATTACHED_FILE_C;
CREATE TABLE TB_ATTACHED_FILE_C (
	FILE_NO	        NUMBER	        NOT NULL,
	POST_NO     	NUMBER	        NOT NULL,
	USER_NO	        NUMBER	        NOT NULL,
	FILE_NAME	    VARCHAR2(255)	DEFAULT '' NOT NULL,
	MFILE_NAME	    VARCHAR2(255)	DEFAULT '' NOT NULL,
    CONSTRAINT PK_TB_ATTACHED_FILE_C PRIMARY KEY(FILE_NO),
    CONSTRAINT FK_TB_ATTACHED_FILE_C FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);

DROP SEQUENCE SEQ_CHA_FNO;
CREATE SEQUENCE SEQ_CHA_FNO;

--챌린지 스크랩 테이블 생성
DROP TABLE TB_SCRAP_C;

CREATE TABLE TB_SCRAP_C (
	SCRAP_NO	    NUMBER	    NOT NULL,
	USER_NO	        NUMBER	    NOT NULL,
	POST_NO	        NUMBER	    NOT NULL,
	USER_NO2     	NUMBER	    NOT NULL,
	SCARP_DATE	    TIMESTAMP	DEFAULT SYSDATE NOT NULL,
	DEL_YN	        CHAR(1)	    DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_SCRAP_C PRIMARY KEY(SCRAP_NO),
    CONSTRAINT FK_TB_SCRAP_C FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);
ALTER TABLE TB_SCRAP_C ADD CONSTRAINT FK_TB_USER_TO_TB_SCRAP_C_1 FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

DROP SEQUENCE SEQ_CHA_SNO;
CREATE SEQUENCE SEQ_CHA_SNO;

--챌린지 게시글 참가 테이블
DROP TABLE TB_PARTICIPATE_C;

CREATE TABLE TB_PARTICIPATE_C (
	PARTI_NO	NUMBER		NOT NULL,
	POST_NO	    NUMBER		NOT NULL,
	USER_NO	    NUMBER		NOT NULL,
	PARTI_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	STOP_YN	CHAR(1)	DEFAULT 'N' CHECK(STOP_YN IN('Y', 'N')),
    USER_NO2    NUMBER	    NOT NULL,
    CONSTRAINT PK_TB_PARTICIPATE_C PRIMARY KEY(PARTI_NO),
    CONSTRAINT FK_TB_PARTICIPATE_C FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);

ALTER TABLE TB_PARTICIPATE_C ADD CONSTRAINT FK_TB_USER_TO_TB_PARTICIPATE_C FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

DROP SEQUENCE SEQ_CHA_PARNO;
CREATE SEQUENCE SEQ_CHA_PARNO;

--챌린지 댓글 추천
DROP TABLE TB_RECOMMEND_COMMENT_C;

CREATE TABLE TB_RECOMMEND_COMMENT_C (
	RECOM_NO	NUMBER		NOT NULL,
	COMM_NO	    NUMBER		NOT NULL,
	POST_NO	    NUMBER		NOT NULL,
	USER_NO	    NUMBER		NOT NULL,
	RECOM_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	DEL_YN	CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    USER_NO2    NUMBER	    NOT NULL,
    CONSTRAINT PK_TB_RECOMMEND_COMMENT_C PRIMARY KEY(RECOM_NO),
    CONSTRAINT FK_TB_RECOMMEND_COMMENT_C FOREIGN KEY(COMM_NO)
    REFERENCES TB_COMMENT_C(COMM_NO),
    FOREIGN KEY (POST_NO) REFERENCES TB_COMMENT_C,
    FOREIGN KEY (USER_NO) REFERENCES TB_COMMENT_C
);

ALTER TABLE TB_RECOMMEND_COMMENT_C
ADD CONSTRAINT USER_NO2 FOREIGN KEY(USER_NO2) REFERENCES TB_USER(USER_NO);

DROP SEQUENCE SEQ_CHA_RCNO;
CREATE SEQUENCE SEQ_CHA_RCNO;

--챌린지 신고 관리 테이블
DROP TABLE CHA_REPORT;

CREATE TABLE CHA_REPORT (
	REPORT_NO	NUMBER		NOT NULL,
	POST_NO	    NUMBER		NOT NULL,
	USER_NO	    NUMBER		NOT NULL,
	REPORT_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	COMM_NO	    NUMBER		NOT NULL,
	USER_NO2	NUMBER		NOT NULL,
    CONSTRAINT PK_CHA_REPORT PRIMARY KEY(REPORT_NO),
    CONSTRAINT FK_CHA_REPORT FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);

ALTER TABLE CHA_REPORT ADD CONSTRAINT FK_TB_USER_TO_CHA_REPORT FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

ALTER TABLE CHA_REPORT ADD CONSTRAINT FK_TB_COMMENT_C_TO_CHA_REPORT FOREIGN KEY (COMM_NO)
REFERENCES TB_COMMENT_C (COMM_NO);

--챌린지 신고관리 시퀀스
--SEQ_REPORT



--------------------------------레시피-------------------------------------
--레시피 게시글
DROP TABLE TB_BOARD_RECEIPT;
DROP TABLE TB_BOARD_RECIPE;
CREATE TABLE TB_BOARD_RECIPE (
	POST_NO	    NUMBER		NOT NULL,
	USER_NO	    NUMBER		NOT NULL,
	POST_NAME	VARCHAR2(30)		NOT NULL,
	POST_CONTENT	VARCHAR2(4000)		NULL,
	BEG_DATE	TIMESTAMP	DEFAULT SYSDATE	NULL,
	HITS	    NUMBER	DEFAULT '0',
	RECOM_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	SCRAP_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	COMM_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	REVIEW_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	DIFFICULTY	VARCHAR2(10),
	REQ_TIME	VARCHAR2(10),
	CATEGORY	VARCHAR2(20),
	TAG	VARCHAR2(20),
	THUMBNAIL	VARCHAR2(100),
	MOD_YN	CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	DEL_YN	CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
	FMOD_DATE	TIMESTAMP,
    CONSTRAINT PK_TB_BOARD_RECIPE PRIMARY KEY(POST_NO),
    CONSTRAINT FK_TB_BOARD_RECIPE FOREIGN KEY(USER_NO)
    REFERENCES TB_USER(USER_NO)
);

DROP SEQUENCE SEQ_REC_RNO;
CREATE SEQUENCE SEQ_REC_RNO;

--레시피 댓글
DROP TABLE TB_COMMNET_R;
CREATE TABLE TB_COMMNET_R (
	COMM_NO	        NUMBER	NOT NULL,
	POST_NO	        NUMBER	NOT NULL,
	USER_NO	        NUMBER	NOT NULL,
	COMM_CONTENT	VARCHAR2(4000)	NOT NULL,
	COMM_ORDER	    NUMBER	NOT NULL,
	RECOM_NUM	    NUMBER	DEFAULT '0' NOT NULL,
	BEG_DATE	    TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MOD_DATE	    TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MOD_YN	        CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	DEL_YN	        CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_COMMENT_R PRIMARY KEY(COMM_NO,POST_NO,USER_NO),
    CONSTRAINT FK_TB_COMMENT_R FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE
);

DROP SEQUENCE SEQ_REC_CNO;
CREATE SEQUENCE SEQ_REC_CNO;

--레시피 대댓글
DROP TABLE TB_COMMENT_R2;

CREATE TABLE TB_COMMENT_R2 (
	COMM_NO         NUMBER NOT NULL,
    POST_NO         NUMBER NOT NULL,
    USER_NO         NUMBER NOT NULL,
	COMM_CONTENT	VARCHAR2(4000)	NOT NULL,
	COMM_ORDER	    NUMBER	    NOT NULL,
	RECOM_NUM	    NUMBER	    DEFAULT '0' NOT NULL,
	BEG_DATE	    TIMESTAMP   DEFAULT SYSDATE	NOT NULL,
	MOD_DATE	    TIMESTAMP	DEFAULT SYSDATE NOT NULL,
	MOD_YN	        CHAR(1)	    DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	DEL_YN	        CHAR(1)	    DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N'))
);
ALTER TABLE TB_COMMENT_R2
ADD CONSTRAINT FK_COMMENT_R2
FOREIGN KEY (COMM_NO, POST_NO, USER_NO)
REFERENCES TB_COMMENT_R (COMM_NO, POST_NO, USER_NO);

--레시피 첨부파일
DROP TABLE TB_ATTACHED_FILE_R;

CREATE TABLE TB_ATTACHED_FILE_R (
	FILE_NO	        NUMBER	        NOT NULL,
	POST_NO     	NUMBER	        NOT NULL,
	USER_NO	        NUMBER	        NOT NULL,
	FILE_NAME	    VARCHAR2(255)	DEFAULT '' NOT NULL,
	MFILE_NAME	    VARCHAR2(255)	DEFAULT '' NOT NULL,
    CONSTRAINT PK_TB_ATTACHED_FILE_R PRIMARY KEY(FILE_NO),
    CONSTRAINT FK_TB_ATTACHED_FILE_R FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE
);

DROP SEQUENCE SEQ_REC_FNO;
CREATE SEQUENCE SEQ_REC_FNO;

--레시피 스크랩
DROP TABLE TB_SCRAP_R;
CREATE TABLE TB_SCRAP_R (
	SCRAP_NO	    NUMBER	    NOT NULL,
	USER_NO	        NUMBER	    NOT NULL,
	POST_NO	        NUMBER	    NOT NULL,
	USER_NO2     	NUMBER	    NOT NULL,
	SCARP_DATE	    TIMESTAMP	DEFAULT SYSDATE NOT NULL,
	DEL_YN	        CHAR(1)	    DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_SCRAP_R PRIMARY KEY(SCRAP_NO),
    CONSTRAINT FK_TB_SCRAP_R FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE
);
ALTER TABLE TB_SCRAP_R ADD CONSTRAINT FK_TB_USER_TO_TB_SCRAP_R_1 FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

DROP SEQUENCE SEQ_REC_SNO;
CREATE SEQUENCE SEQ_REC_SNO;

--레시피 게시글 추천
DROP TABLE TB_RECOMMEND_R;

CREATE TABLE TB_RECOMMEND_R (
	RECOM_NO	    NUMBER		NOT NULL,
	POST_NO	        NUMBER		NOT NULL,
	USER_NO	        NUMBER		NOT NULL,
	RECOM_DATE	    TIMESTAMP   DEFAULT SYSDATE NOT NULL,
	DEL_YN	        CHAR(1)	    DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
	USER_NO2	    NUMBER		NOT NULL,
    CONSTRAINT PK_TB_RECOMMEND_R PRIMARY KEY(RECOM_NO),
    CONSTRAINT FK_TB_RECOMMEND_R FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE
);

ALTER TABLE TB_RECOMMEND_R ADD CONSTRAINT FK_TB_USER_TO_TB_RECOMMEND_R FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

DROP SEQUENCE SEQ_REC_RNO;
CREATE SEQUENCE SEQ_REC_RNO;

--레시피 댓글 추천
DROP TABLE TB_RECOMMEND_COMMENT_R;
CREATE TABLE TB_RECOMMEND_COMMENT_R (
	RECOM_NO	NUMBER		NOT NULL,
	COMM_NO	    NUMBER		NOT NULL,
	POST_NO	    NUMBER		NOT NULL,
	USER_NO	    NUMBER		NOT NULL,
	RECOM_DATE	TIMESTAMP   DEFAULT SYSDATE NOT NULL,
	DEL_YN	    CHAR(1)	    DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
	USER_NO2	NUMBER		NOT NULL,
    CONSTRAINT PK_TB_RECOMMEND_COMMENT_R PRIMARY KEY(RECOM_NO)
    --CONSTRAINT FK_TB_RECOMMEND_COMMENT_R FOREIGN KEY(COMM_NO) --외래키 아직 못함 왜인지 안들어가
   -- REFERENCES TB_COMMENT_R(COMM_NO)
    --FOREIGN KEY (POST_NO) REFERENCES TB_COMMENT_R,
   -- FOREIGN KEY (USER_NO) REFERENCES TB_COMMENT_R
);

ALTER TABLE TB_RECOMMEND_COMMENT_R
ADD CONSTRAINT USER_NO2 FOREIGN KEY(USER_NO2) REFERENCES TB_USER(USER_NO);

--레시피 신고 관리
DROP TABLE REC_REPORT;

CREATE TABLE REC_REPORT (
	REPORT_NO	NUMBER		NOT NULL,
	POST_NO	    NUMBER		NOT NULL,
	USER_NO	    NUMBER		NOT NULL,
	REPORT_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	COMM_NO	    NUMBER		NOT NULL,
	USER_NO2	NUMBER		NOT NULL,
    CONSTRAINT PK_REC_REPORT PRIMARY KEY(REPORT_NO),
    CONSTRAINT FK_REC_REPORT FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE
);

ALTER TABLE REC_REPORT ADD CONSTRAINT FK_TB_USER_TO_REC_REPORT FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

--ALTER TABLE REC_REPORT ADD CONSTRAINT FK_TB_COMMENT_R_TO_REC_REPORT FOREIGN KEY (COMM_NO) 제약조건이 안걸림 내가보니 COMM_NO 이녀석이 문제다.
--REFERENCES TB_COMMENT_R (COMM_NO);






COMMIT;



-------------------------------------------------스크립트 끝 밑에서부터는 각자 테이블 컬럼 변경한 거 및 더미데이터 추가 한것.


--메거진 게시판 컬럼 변경 (USER_NO -> ADMIN_NO)
ALTER TABLE TB_BOARD_MAGAZINE DROP COLUMN USER_NO;

ALTER TABLE TB_BOARD_MAGAZINE ADD(ADMIN_NO NUMBER); 

ALTER TABLE TB_BOARD_MAGAZINE ADD CONSTRAINT FK_TB_BOARD_MAGAZINE FOREIGN KEY (ADMIN_NO)
REFERENCES TB_ADMIN(ADMIN_NO);

COMMIT;

--메거진 데이터 생성
INSERT INTO TB_BOARD_MAGAZINE(
    POST_NO,POST_NAME,POST_CONTENT,BEG_DATE,
	HITS,RECOM_NUM,SCRAP_NUM,COMM_NUM,MOD_YN,FMOD_DATE,DEL_YN,ADMIN_NO
)VALUES(
    SEQ_MAG_PNO.NEXTVAL,'한우자조금, 홈파티용 한우 레시피 소개','외부 활동이 어려운 이때 한우자조금이 한우를 활용한 작은 홈파티용 레시피를 공개해 주목되고 있다.
한우자조금 관리위원회(위원장 민경천)는 최근 홈페이지 ‘한우유명한곳’을 통해 홈파티용 한우레시피를 소개했다. 한우 앞다리살을 채썰어 육회 조리법에 따라 설탕, 소금, 후추, 간장, 다진 마늘 등으로 밑간을 한다. 여기에 트러플 오일을 고추장과 함께 넣고 버무려 주면 특별한 향의 한우육회가 완성된다.',default,default,default,default,
    default,default,default,DEFAULT,'1'
    );
    
INSERT INTO TB_BOARD_MAGAZINE(
    POST_NO,POST_NAME,POST_CONTENT,BEG_DATE,
	HITS,RECOM_NUM,SCRAP_NUM,COMM_NUM,MOD_YN,FMOD_DATE,DEL_YN,ADMIN_NO
)VALUES(
    SEQ_MAG_PNO.NEXTVAL,'닭가슴살에 마늘... 백종원 레시피에도 없는 "치킨국"','조물주가 나를 만들 때 대체 무슨 일이 있었던 건지 깜빡하고 넣지 않은 것이 많다. 계산하는 능력, 길 찾는 법, 기계를 조작하는 법 등 많은 것을 빼먹었는데, 그중에서도 "요리 실력"은 아예 넣을 생각도 하지 않았던 게 틀림없다. 요리라는 말만 나와도 숨이 답답하고 머릿속이 캄캄해지는 것이 바로 그 이유이다.  

이런 내가 15년간, 식구들의 밥을 책임져 왔다는 것은 거의 기적에 가까운 일이자 한편으로 미안한 일이 아닐 수 없다.',default,default,default,default,
    default,default,default,DEFAULT,'2'
    );
    
    INSERT INTO TB_BOARD_MAGAZINE(
    POST_NO,POST_NAME,POST_CONTENT,BEG_DATE,
	HITS,RECOM_NUM,SCRAP_NUM,COMM_NUM,MOD_YN,FMOD_DATE,DEL_YN,ADMIN_NO
)VALUES(
    SEQ_MAG_PNO.NEXTVAL,'외국인 입맛 잡는 고추장 "마법의 레시피"','맛보다 거의 때우기 식으로 차려내다 보니 먹는 즐거움을 제공하지 못했다. 보다 못한 남편이 얼마 전부터 주방을 책임지고 있는데 결국 답답한 놈이 우물을 판다는 말이 사실이었다.

나만의 필살기 요리, 아주 쉽습니다',default,default,default,default,
    default,default,default,DEFAULT,'1'
    );

INSERT INTO TB_BOARD_MAGAZINE(
    POST_NO,POST_NAME,POST_CONTENT,BEG_DATE,
	HITS,RECOM_NUM,SCRAP_NUM,COMM_NUM,MOD_YN,FMOD_DATE,DEL_YN,ADMIN_NO
)VALUES(
    SEQ_MAG_PNO.NEXTVAL,'[보고서]규칙적인 식습관의 중요성','현대인들의 식습관이 무차별적이고 무자비하다',default,default,default,default,
    default,default,default,DEFAULT,'1'
    );

INSERT INTO TB_BOARD_MAGAZINE(
    POST_NO,POST_NAME,POST_CONTENT,BEG_DATE,
	HITS,RECOM_NUM,SCRAP_NUM,COMM_NUM,MOD_YN,FMOD_DATE,DEL_YN,ADMIN_NO
)VALUES(
    SEQ_MAG_PNO.NEXTVAL,'"음식만 보여줬는데"…조리법 익혀 요리 뚝딱, 사람이 아니네','"증강현실(AR) 글라스를 착용하고 온라인 쇼핑을 하고, 인공지능(AI) 로봇이 레시피를 연구해 요리한다."

테크놀로지 업계의 새해로 불리는 소비자가전전시회(CES)가 "일상을 넘어서(Beyond the Everyday)"라는 주제로 오는 5일 미국 라스베이거스에서 성대한 막을 올린다. "일상을 넘어"라는 모토는 테크놀로지가 현실 속 깊이 파고드는 것을 뛰어넘어, 이제는 가상현실(VR)로 안내하고 있다는 의미를 담았다. 올해 CES는 그동안 주요 영역이었던 사물인터넷(IoT), 가전, 모빌리티 외에도 대체불가토큰(NFT), 메타버스, 푸드테크, 우주 기술과 같은 새로운 영역을 대거 추가했다.',default,default,default,default,
    default,default,default,DEFAULT,'1'
    );

INSERT INTO TB_BOARD_MAGAZINE(
    POST_NO,POST_NAME,POST_CONTENT,BEG_DATE,
	HITS,RECOM_NUM,SCRAP_NUM,COMM_NUM,MOD_YN,FMOD_DATE,DEL_YN,ADMIN_NO
)VALUES(
    SEQ_MAG_PNO.NEXTVAL,'덜덜 떨면서 먹어야 제 맛.. "얼어 죽어도 포기 못해"','26일 서울 아침 최저기온이 영하 15도까지 곤두박질쳤다. 한겨울로 깊숙이 진입한 모양새다. 습관처럼 켜놓은 TV 화면에는 목도리 등으로 칭칭 감싼 차림새로 얼굴조차 분간하기 어려운 기상 캐스터가 등장해 올 겨울 들어 가장 추운 날씨를 실감나게 전하고 있었다. 덕분에 잊고 지내온 한겨울의 느낌이 온전히 되살아나는 것 같다. 이런 날에는 움직임 자체가 무척 곤혹스럽다. 일요일인 게 천만다행이다. ',default,default,default,default,
    default,default,default,DEFAULT,'1'
    );
    
    INSERT INTO TB_BOARD_MAGAZINE(
    POST_NO,POST_NAME,POST_CONTENT,BEG_DATE,
	HITS,RECOM_NUM,SCRAP_NUM,COMM_NUM,MOD_YN,FMOD_DATE,DEL_YN,ADMIN_NO
)VALUES(
    SEQ_MAG_PNO.NEXTVAL,'“건강식품 ‘마’젤리로 제품화된다!”','경상북도농업기술원(생물자원연구소)은 1월 5일 안동에서‘조직감이 개선된 마 젤리 및 제조방법(출원 2021-0139517)’에 대한 특허기술을 안동와룡농협에 이전하는 협약식을 개최했다.
이를 통해 주로 생식이나 한약재로만 사용되던 마를 먹기 좋게 가공해 제품화하면 소비 확대에 도움이 될 전망이다.',default,default,default,default,
    default,default,default,DEFAULT,'1'
    );
    

commit;


------------------------------------메거진 끝

---------------지은님 파트 admin, support
ALTER TABLE TB_NOTICE MODIFY MOD_DATE DEFAULT NULL;
ALTER TABLE TB_QNA MODIFY MOD_DATE DEFAULT NULL;
ALTER TABLE TB_REPORT MODIFY MOD_DATE DEFAULT NULL;

DROP SEQUENCE SEQ_ADMIN;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_NOTICE_ATTACHMENT;
DROP SEQUENCE SEQ_QNA;
DROP SEQUENCE SEQ_QNA_ATTACHMENT;
DROP SEQUENCE SEQ_REPORT;
DROP SEQUENCE SEQ_REPORT_ATTACHMENT;

CREATE SEQUENCE SEQ_ADMIN NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE_ATTACHMENT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_QNA NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_QNA_ATTACHMENT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REPORT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REPORT_ATTACHMENT NOCACHE NOCYCLE;

INSERT INTO TB_ADMIN (
   ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
   ) VALUES (
   SEQ_ADMIN.NEXTVAL, 'adminS',  'seo',  '서성환', 'Lv1', DEFAULT, DEFAULT );
INSERT INTO TB_ADMIN (
   ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
   ) VALUES (
   SEQ_ADMIN.NEXTVAL, 'adminL',  'lee',  '이지은', 'Lv2', DEFAULT, DEFAULT );
INSERT INTO TB_ADMIN (
   ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
   ) VALUES (
   SEQ_ADMIN.NEXTVAL, 'adminC',  'cha',  '차세희', 'Lv1', DEFAULT, DEFAULT );
INSERT INTO TB_ADMIN (
   ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
   ) VALUES (
   SEQ_ADMIN.NEXTVAL, 'adminJ',  'jang',  '장재욱', 'Lv2', DEFAULT, DEFAULT );
INSERT INTO TB_ADMIN (
   ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
   ) VALUES (
   SEQ_ADMIN.NEXTVAL, 'adminH',  'ha',  '이주하', 'Lv1', DEFAULT, DEFAULT );
INSERT INTO TB_ADMIN (
   ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
   ) VALUES (
   SEQ_ADMIN.NEXTVAL, 'adminT',  'two',  '심투용', DEFAULT, DEFAULT, DEFAULT );

INSERT INTO TB_NOTICE (
   NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, HITS, MOD_YN, MOD_DATE, DELETE_YN
   ) VALUES (
   SEQ_NOTICE.NEXTVAL, '레시피토리 오픈 안내',  '안녕하세요? 레시피토리입니다. 드디어 레시피토리 사이트가 오픈 되었습니다! 오픈 초리가 다소 미흡한 부분이 발견되더라도 너그러운 양해부탁드리며, 원활한 서비스 이용을 위해 신속히 대처하겠습니다. 현재 새로운 기능을 오픈 준비 중이며, 서비스가 안정화 되는대로 다시 찾아뵙겠습니다. 회원 여러분들의 많은 성원과 참여 부탁드립니다. 서비스 이용 중 불편한 사항이나 건의사항은 고객문의에 남겨주시면, 최대한 신속히 답변드리겠습니다. 감사합니다.', '1', '21/12/01 00:36:29.000000000', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
   NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, HITS,  MOD_YN, MOD_DATE, DELETE_YN
   ) VALUES (
   SEQ_NOTICE.NEXTVAL, '레시피 상세조회 오류 조치 안내',  '안녕하세요. 레시피토리입니다. 1일 자정부터 레시피 상세보기에 오류가 발생하였습니다. 먼저 서비스 이용에 불편을 드린 점 깊이 사과드리며, 오류 확인 후 조치하여 새벽 1시경에 정상화 되었습니다. 즉각적인 오류신고를 해주신 회원님들께 진심으로 감사드립니다. 더 나은 서비스 제공 뿐만 아니라 원활한 서비스 이용이 될 수 있도록 운영에 더욱 만전을 기하겠습니다. 감사합니다.', '2', '21/12/02 00:55:49.000000000', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
   NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, HITS,  MOD_YN, MOD_DATE, DELETE_YN
   ) VALUES (
   SEQ_NOTICE.NEXTVAL, '개인정보처리방침 변경 안내',  '안녕하세요. <레시피토리 개인정보처리방침>이 2022년 01월 03일자로 변경됩니다. 회원 여러분들께서는 변경되는 내용을 참고하시어 서비스 이용에 불편이 없으시길 바랍니다.', '2','21/12/03 00:55:49.000000000', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
   NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, HITS,  MOD_YN, MOD_DATE, DELETE_YN
   ) VALUES (
   SEQ_NOTICE.NEXTVAL, '서비스 개편 및 이용안내',  '안녕하세요. 레시피토리입니다. 새롭게 개편된 매거진 메뉴를 통해 재철 식재료 및 음식 관련 다양한 정보를 보다 쉽게 확인하실 수 있습니다. 관련 문의사항이나 건의사항은 언제든 고객문의에 남겨주세요. 감사합니다.', '3', '21/12/05 00:20:12.000000000', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
   NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, HITS,  MOD_YN, MOD_DATE, DELETE_YN
   ) VALUES (
   SEQ_NOTICE.NEXTVAL, '고객센터 이용안내',  '레시피토리 고객센터(02-1234-2334) / 상담시간: 오전 10 - 오후 5시', '3', '21/12/22 00:55:49.000000000', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
   NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, HITS,  MOD_YN, MOD_DATE, DELETE_YN
   ) VALUES (
   SEQ_NOTICE.NEXTVAL, '01/01 서비스 점검안내',  '안녕하세요. 레시피토리 운영팀입니다. 서비스 점검으로 인하여 점검 시간 동안 정상적인 서비스 이용이 불가한 점 안내드립니다. <서비스 점검시간 : 2022년 01월 01일 오전 06시 00분 ~ 오전 09시 00분까지> 점검 상황에 따라 점검 종료시간이 다소 지연될 수 있습니다. 감사합니다.', '2', '21/12/30 00:25:19.000000000', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
   NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, HITS,  MOD_YN, MOD_DATE, DELETE_YN
   ) VALUES (
   SEQ_NOTICE.NEXTVAL, '01/03 서버 장애 정상화 안내드립니다',  '안녕하세요. 레시피토리입니다. 금일 새벽부터 아침까지 서버 장애로 인하여 서비스 이용에 불편을 드린 점 깊이 사과드립니다. 서비스 정상화 조치 이후 기타 오류 등이 없는지 세부적인 점검을 통하여 정상화 작업을 마무리할 예정입니다. 감사합니다.', '1', '22/01/03 00:33:19.000000000', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
   NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, HITS,  MOD_YN, MOD_DATE, DELETE_YN
   ) VALUES (
   SEQ_NOTICE.NEXTVAL, '[안내] 코로나19 격상에 따른 문의 안내',  '안녕하세요. 레시피토리입니다. 코로나 19 위기 대응 단계가 심각으로 격상됨에 따라 추가 확산과 감염 예방을 위해 레시피토리가 재택근무에 들어가게 되었습니다. 전화 문의 응대가 불가능해진 관계로 문의글을 남겨주시면 확인 후 조치하도록 하겠습니다.', '4', '22/01/04 00:33:19.000000000', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
   NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, HITS,  MOD_YN, MOD_DATE, DELETE_YN
   ) VALUES (
   SEQ_NOTICE.NEXTVAL, '[안내] 신규 서비스 <챌린지> 오픈 안내',  '안녕하세요. 레시피토리에서 새로운 서비스 <챌린지>를 오픈했습니다. 챌린지는 요리, 건강에 관련된 챌린지를 공유하여 토리식구들과 함께 으쌰으쌰 할 수 있는 서비스를 제공해드리는 서비스입니다. 많은 기대와 관심 부탁드립니다.', '3', '22/01/05 20:13:19.000000000', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
   NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, HITS,  MOD_YN, MOD_DATE, DELETE_YN
   ) VALUES (
   SEQ_NOTICE.NEXTVAL, '닉네임 변경 기능 추가',  '안녕하세요. 레시피토리에서 새로운 기능인 닉네임 변경기능이 추가되었습니다. 자신을 상징하는 이름으로 바꿔보세요~! 감사합니다.', '5', '22/01/05 30:18:19.000000000', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
   
INSERT INTO TB_QNA (
   QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, ADMIN_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
   ) VALUES (
   SEQ_QNA.NEXTVAL, '회원가입 문의',  '회원가입하고싶은데 어떻게 하나요?', '5', '1', '21/12/22 19:53:26.000000000', DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_QNA (
   QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, ADMIN_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
   ) VALUES (
   SEQ_QNA.NEXTVAL, '레시피 올리는 방법',  '사진을 첨부하고 싶어요', '4', '1', '21/12/30 20:23:12.000000000', DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_QNA (
   QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, ADMIN_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
   ) VALUES (
   SEQ_QNA.NEXTVAL, '비밀번호 변경',  '비밀번호를 보안상 변경하고싶습니다.', '3', '3', '22/01/01 11:22:07.000000000', DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_QNA (
   QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, ADMIN_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
   ) VALUES (
   SEQ_QNA.NEXTVAL, '레시피 수정',  '레시피를 한 번 등록하면 수정이 되나요?', '2', '2', '22/01/03 10:54:09.000000000', DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_QNA (
   QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, ADMIN_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
   ) VALUES (
   SEQ_QNA.NEXTVAL,'동영상 첨부 방법 문의',  '사진말고 영상도 첨부가 되는지 궁금해요', '1', '1', '22/01/05 34:35:11.000000000', DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO TB_REPORT (
   REPORT_NO, REPORT_TITLE, REPORT_CONTENT, USER_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
   ) VALUES (
   SEQ_REPORT.NEXTVAL,'게시글 신고',  '레시피가 아닌 글이 레시피 게시판에 올라와있어요. ', '1', '21/12/25 12:25:11.000000000', DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_REPORT (
   REPORT_NO, REPORT_TITLE, REPORT_CONTENT, USER_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
   ) VALUES (
   SEQ_REPORT.NEXTVAL,'회원 신고',  '댓글에 욕설을 쓰신 회원분을 신고하고싶습니다.', '3', '22/01/01 00:02:23.000000000','답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_REPORT (
   REPORT_NO, REPORT_TITLE, REPORT_CONTENT, USER_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
   ) VALUES (
   SEQ_REPORT.NEXTVAL,'댓글 신고',  '비방 댓글을 신고합니다.', '5', '22/01/03 01:00:11.000000000', DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_REPORT (
   REPORT_NO, REPORT_TITLE, REPORT_CONTENT, USER_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
   ) VALUES (
   SEQ_REPORT.NEXTVAL,'적절하지 못한 게시글',  '적절하지 못한 사진이 첨부되어있는 글을 발견했습니다.', '6','22/01/04 00:23:05.000000000', DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_REPORT (
   REPORT_NO, REPORT_TITLE, REPORT_CONTENT, USER_NO, CREATE_DATE, HITS, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
   ) VALUES (
   SEQ_REPORT.NEXTVAL,'비방 댓글 신고',  '깨끗한 댓글문화를 만들어가기위해 이 회원을 신고합니다.', '7', '22/01/05 34:35:11.000000000', DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);

   commit;
   
   
-------------------주하님 user테이블 더미 데이터 추가.
   
INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'iuser1', 'iuser@1111', '곤약', 'iuser1@gmail.com', '01011111111', SYSDATE, DEFAULT, 'N', SYSDATE);

INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'iuser2', 'iuser@2222', '고수', 'iuser2@gmail.com', '01022222222', SYSDATE, DEFAULT, 'N', SYSDATE);

INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'iuser3', 'iuser@3333', '은행', 'iuser3@gmail.com', '01033333333', SYSDATE, DEFAULT, 'N', SYSDATE);

INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'iuser4', 'iuser@4444', '생양파', 'iuser4@gmail.com', '01044444444', SYSDATE, DEFAULT, 'N', SYSDATE);

INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'iuser5', 'iuser@5555', '아보카도', 'iuser5@gmail.com', '01055555555', SYSDATE, DEFAULT, 'N', SYSDATE);



   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'iuser6', 'iuser@6666', '타코', 'iuser6@gmail.com', '01066666666', SYSDATE, DEFAULT, 'N', SYSDATE);
   
   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'iuser7', 'iuser@7777', '초밥', 'iuser7@gmail.com', '01077777777', SYSDATE, DEFAULT, 'N', SYSDATE);
   
   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'iuser8', 'iuser@8888', '두부', 'iuser8@gmail.com', '01088888888', SYSDATE, DEFAULT, 'N', SYSDATE);
   
   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'iuser9', 'iuser@9999', '수박', 'iuser9@gmail.com', '01099999999', SYSDATE, DEFAULT, 'N', SYSDATE);
   
   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'iuser0', 'iuser@0000', '자전거', 'iuser0@gmail.com', '01000000000', SYSDATE, DEFAULT, 'N', SYSDATE);
   


   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'user01', 'user111', '백호', 'user01@gmail.com', '01012345678', SYSDATE, DEFAULT, 'N', SYSDATE);
   
   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'user02', 'user222', '사자', 'user02@gmail.com', '01087654321', SYSDATE, DEFAULT, 'N', SYSDATE);
   
   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'user03', 'user333', '미어캣', 'user03@gmail.com', '01013132424', SYSDATE, DEFAULT, 'N', SYSDATE);
   
   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'user04', 'user444', '핫도그', 'user04@gmail.com', '01035354646', SYSDATE, DEFAULT, 'N', SYSDATE);
   
   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'user05', 'user555', '햄토리', 'user05@gmail.com', '01057576868', SYSDATE, DEFAULT, 'N', SYSDATE);
   
   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'user06', 'user666', '고라니', 'user06@gmail.com', '01079798080', SYSDATE, DEFAULT, 'N', SYSDATE);
   
   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'user07', 'user777', '붕어빵', 'user07@gmail.com', '01012221222', SYSDATE, DEFAULT, 'N', SYSDATE);
   
   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'user08', 'user888', '다람이', 'user08@gmail.com', '01032123212', SYSDATE, DEFAULT, 'N', SYSDATE);
   
   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'user09', 'user999', '기린', 'user09@gmail.com', '01055456565', SYSDATE, DEFAULT, 'N', SYSDATE);
   
   INSERT INTO TB_USER (
   USER_NO, USER_ID, USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
   ) VALUES (
   SEQ_UNO.NEXTVAL, 'user10', 'user000', '죠스바', 'user10@gmail.com', '01079797979', SYSDATE, DEFAULT, 'N', SYSDATE);
   

   
   COMMIT;
   
   
   ----------------------recipe 테이블 관련 재욱님.
   
   --레시피 게시글
DROP TABLE TB_BOARD_RECEIPT;
DROP TABLE TB_BOARD_RECIPE;
CREATE TABLE TB_BOARD_RECIPE2 (
   POST_NO       NUMBER      NOT NULL,
   USER_NO       NUMBER      NOT NULL,
   POST_NAME   VARCHAR2(30)      NOT NULL,
   BEG_DATE   TIMESTAMP   DEFAULT SYSDATE,
    INGREDIENT1 VARCHAR2(30)    NULL,
    INGREDIENT2 VARCHAR2(30)    NULL,
    INGREDIENT3 VARCHAR2(30)    NULL,
    INGREDIENT4 VARCHAR2(30)    NULL,
    INGREDIENT5 VARCHAR2(30)    NULL,
    POST_CONTENT1   VARCHAR2(4000)      NULL,
    POST_CONTENT2   VARCHAR2(4000)      NULL,
    POST_CONTENT3   VARCHAR2(4000)      NULL,
    POST_CONTENT4   VARCHAR2(4000)      NULL,
    POST_CONTENT5   VARCHAR2(4000)      NULL,
   THUMBNAIL   VARCHAR2(100),
   MOD_YN   CHAR(1)   DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
   DEL_YN   CHAR(1)   DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
   FMOD_DATE   TIMESTAMP,
    CONSTRAINT PK_TB_BOARD_RECIPE2 PRIMARY KEY(POST_NO),
    CONSTRAINT FK_TB_BOARD_RECIPE2 FOREIGN KEY(USER_NO)
    REFERENCES TB_USER(USER_NO)
);

DROP SEQUENCE SEQ_REC_RNO;
CREATE SEQUENCE SEQ_REC_RNO NOCYCLE NOCACHE;

--레시피 댓글
DROP TABLE TB_COMMNET_R;
CREATE TABLE TB_COMMNET_R (
   COMM_NO           NUMBER   NOT NULL,
   POST_NO           NUMBER   NOT NULL,
   USER_NO           NUMBER   NOT NULL,
   COMM_CONTENT   VARCHAR2(4000)   NOT NULL,
   COMM_ORDER       NUMBER   NOT NULL,
   RECOM_NUM       NUMBER   DEFAULT '0' NOT NULL,
   BEG_DATE       TIMESTAMP DEFAULT SYSDATE NOT NULL,
   MOD_DATE       TIMESTAMP DEFAULT SYSDATE NOT NULL,
   MOD_YN           CHAR(1)   DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
   DEL_YN           CHAR(1)   DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_COMMENT_R PRIMARY KEY(COMM_NO,POST_NO,USER_NO),
    CONSTRAINT FK_TB_COMMENT_R FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE2(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE2
);

DROP SEQUENCE SEQ_REC_CNO;
CREATE SEQUENCE SEQ_REC_CNO;

--레시피 대댓글
DROP TABLE TB_COMMENT_R2;

CREATE TABLE TB_COMMENT_R2 (
   COMM_NO         NUMBER NOT NULL,
    POST_NO         NUMBER NOT NULL,
    USER_NO         NUMBER NOT NULL,
   COMM_CONTENT   VARCHAR2(4000)   NOT NULL,
   COMM_ORDER       NUMBER       NOT NULL,
   RECOM_NUM       NUMBER       DEFAULT '0' NOT NULL,
   BEG_DATE       TIMESTAMP   DEFAULT SYSDATE   NOT NULL,
   MOD_DATE       TIMESTAMP   DEFAULT SYSDATE NOT NULL,
   MOD_YN           CHAR(1)       DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
   DEL_YN           CHAR(1)       DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N'))
);
ALTER TABLE TB_COMMENT_R2
ADD CONSTRAINT FK_COMMENT_R2
FOREIGN KEY (COMM_NO, POST_NO, USER_NO)
REFERENCES TB_COMMENT_R (COMM_NO, POST_NO, USER_NO);

--레시피 첨부파일
DROP TABLE TB_ATTACHED_FILE_R;

CREATE TABLE TB_ATTACHED_FILE_R (
   FILE_NO           NUMBER           NOT NULL,
   POST_NO        NUMBER           NOT NULL,
   USER_NO           NUMBER           NOT NULL,
   MFILE_NAME       VARCHAR2(255)   DEFAULT '' NOT NULL,
    CONSTRAINT PK_TB_ATTACHED_FILE_R PRIMARY KEY(FILE_NO),
    CONSTRAINT FK_TB_ATTACHED_FILE_R FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE2(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE2
);

DROP SEQUENCE SEQ_REC_FNO;
CREATE SEQUENCE SEQ_REC_FNO NOCYCLE NOCACHE;

--레시피 스크랩
DROP TABLE TB_SCRAP_R;
CREATE TABLE TB_SCRAP_R (
   SCRAP_NO       NUMBER       NOT NULL,
   USER_NO           NUMBER       NOT NULL,
   POST_NO           NUMBER       NOT NULL,
   USER_NO2        NUMBER       NOT NULL,
   SCARP_DATE       TIMESTAMP   DEFAULT SYSDATE NOT NULL,
   DEL_YN           CHAR(1)       DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_SCRAP_R PRIMARY KEY(SCRAP_NO),
    CONSTRAINT FK_TB_SCRAP_R FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE2(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE2
);
ALTER TABLE TB_SCRAP_R ADD CONSTRAINT FK_TB_USER_TO_TB_SCRAP_R_1 FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

DROP SEQUENCE SEQ_REC_SNO;
CREATE SEQUENCE SEQ_REC_SNO;

--레시피 게시글 추천
DROP TABLE TB_RECOMMEND_R;

CREATE TABLE TB_RECOMMEND_R (
   RECOM_NO       NUMBER      NOT NULL,
   POST_NO           NUMBER      NOT NULL,
   USER_NO           NUMBER      NOT NULL,
   RECOM_DATE       TIMESTAMP   DEFAULT SYSDATE NOT NULL,
   DEL_YN           CHAR(1)       DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
   USER_NO2       NUMBER      NOT NULL,
    CONSTRAINT PK_TB_RECOMMEND_R PRIMARY KEY(RECOM_NO),
    CONSTRAINT FK_TB_RECOMMEND_R FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE2(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE2
);

ALTER TABLE TB_RECOMMEND_R ADD CONSTRAINT FK_TB_USER_TO_TB_RECOMMEND_R FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

DROP SEQUENCE SEQ_REC_RNO;
CREATE SEQUENCE SEQ_REC_RNO;

--레시피 댓글 추천
DROP TABLE TB_RECOMMEND_COMMENT_R;
CREATE TABLE TB_RECOMMEND_COMMENT_R (
   RECOM_NO   NUMBER      NOT NULL,
   COMM_NO       NUMBER      NOT NULL,
   POST_NO       NUMBER      NOT NULL,
   USER_NO       NUMBER      NOT NULL,
   RECOM_DATE   TIMESTAMP   DEFAULT SYSDATE NOT NULL,
   DEL_YN       CHAR(1)       DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
   USER_NO2   NUMBER      NOT NULL,
    CONSTRAINT PK_TB_RECOMMEND_COMMENT_R PRIMARY KEY(RECOM_NO)
    --CONSTRAINT FK_TB_RECOMMEND_COMMENT_R FOREIGN KEY(COMM_NO) --외래키 아직 못함 왜인지 안들어가
   -- REFERENCES TB_COMMENT_R(COMM_NO)
    --FOREIGN KEY (POST_NO) REFERENCES TB_COMMENT_R,
   -- FOREIGN KEY (USER_NO) REFERENCES TB_COMMENT_R
);

ALTER TABLE TB_RECOMMEND_COMMENT_R
ADD CONSTRAINT USER_NO2 FOREIGN KEY(USER_NO2) REFERENCES TB_USER(USER_NO);

--레시피 신고 관리
DROP TABLE REC_REPORT;

CREATE TABLE REC_REPORT (
   REPORT_NO   NUMBER      NOT NULL,
   POST_NO       NUMBER      NOT NULL,
   USER_NO       NUMBER      NOT NULL,
   REPORT_DATE   TIMESTAMP   DEFAULT SYSDATE   NOT NULL,
   COMM_NO       NUMBER      NOT NULL,
   USER_NO2   NUMBER      NOT NULL,
    CONSTRAINT PK_REC_REPORT PRIMARY KEY(REPORT_NO),
    CONSTRAINT FK_REC_REPORT FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE2(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE2
);

ALTER TABLE REC_REPORT ADD CONSTRAINT FK_TB_USER_TO_REC_REPORT FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

--ALTER TABLE REC_REPORT ADD CONSTRAINT FK_TB_COMMENT_R_TO_REC_REPORT FOREIGN KEY (COMM_NO) 제약조건이 안걸림 내가보니 COMM_NO 이녀석이 문제다.
--REFERENCES TB_COMMENT_R (COMM_NO);



COMMIT;


--------챌린지 게시판 차세희님.

--스크랩 삭제
DROP TABLE TB_SCRAP_C;

--챌린지 게시판(삭제)
DROP TABLE TB_BOARD_CHALLENGE;
--CREATE TABLE TB_BOARD_CHALLENGE (
--	POST_NO	NUMBER		NOT NULL,
--	USER_NO	NUMBER		NOT NULL,
--	POST_NAME	VARCHAR2(30)		NOT NULL,
--	POST_CONTENT	VARCHAR2(4000)		NOT NULL,
--	BEG_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
--	CHALLENGE_PERIOD	DATE,
--	PARTI_NUM	NUMBER	DEFAULT '0'	NOT NULL,
--	REVIEW_NUM	NUMBER	DEFAULT '0'	NOT NULL,
--	THUMBNAIL	VARCHAR2(100),
--	MOD_YN	CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
--	FMOD_DATE	TIMESTAMP   DEFAULT SYSDATE,
--	DEL_YN	CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
--    CONSTRAINT PK_TB_BOARD_CHALLENGE PRIMARY KEY(POST_NO),
--    CONSTRAINT FK_TB_BOARD_CHALLENGE FOREIGN KEY(USER_NO) REFERENCES TB_USER(USER_NO)
--);
--
--DROP SEQUENCE SEQ_CHA_PNO;
--CREATE SEQUENCE SEQ_CHA_PNO NOCYCLE NOCACHE;

----새로운 챌린지 게시판 테이블
DROP TABLE TB_POST_C;
CREATE TABLE TB_POST_C (
	POST_NO	NUMBER		NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	POST_NAME	VARCHAR2(30)		NOT NULL,
	POST_CONTENT	VARCHAR2(4000)		NOT NULL,
	BEG_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	CHALLENGE_PERIOD	DATE,
	PARTI_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	REVIEW_NUM	NUMBER	DEFAULT '0'	NOT NULL,
	THUMBNAIL	VARCHAR2(100),
	MOD_YN	CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	FMOD_DATE	TIMESTAMP   DEFAULT SYSDATE,
	DEL_YN	CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_POST_C PRIMARY KEY(POST_NO),
    CONSTRAINT FK_TB_POST_C FOREIGN KEY(USER_NO) REFERENCES TB_USER(USER_NO)
);
DROP SEQUENCE SEQ_CHA_PTO;
CREATE SEQUENCE SEQ_CHA_PTO;

----챌린지 댓글
DROP TABLE TB_COMMENT_C;
CREATE TABLE TB_COMMENT_C (
	COMM_NO	        NUMBER	NOT NULL,
	POST_NO	        NUMBER	NOT NULL,
	USER_NO	        NUMBER	NOT NULL,
	COMM_CONTENT	VARCHAR2(4000)	NOT NULL,
	COMM_ORDER	    NUMBER	NOT NULL,
	RECOM_NUM	    NUMBER	DEFAULT '0' NOT NULL,
	BEG_DATE	    TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MOD_DATE	    TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MOD_YN	        CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	DEL_YN	        CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_COMMENT_C PRIMARY KEY(COMM_NO),
    CONSTRAINT FK_TB_COMMENT_C FOREIGN KEY(POST_NO) REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);
---- 챌린지 대댓글
DROP TABLE TB_COMMENT_C2;
CREATE TABLE TB_COMMENT_C2 (
	COMM_NO NUMBER NOT NULL,
    POST_NO NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
	COMM_CONTENT	VARCHAR2(4000)	NOT NULL,
	COMM_ORDER	NUMBER	    NOT NULL,
	RECOM_NUM	NUMBER	    DEFAULT '0' NOT NULL,
	BEG_DATE	TIMESTAMP   DEFAULT SYSDATE	NOT NULL,
	MOD_DATE	TIMESTAMP	DEFAULT SYSDATE NOT NULL,
	MOD_YN	    CHAR(1)	    DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	DEL_YN	    CHAR(1)	    DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT FK_TB_COMMENT_C2 FOREIGN KEY(COMM_NO) REFERENCES TB_COMMENT_C(COMM_NO),
    FOREIGN KEY (POST_NO) REFERENCES TB_COMMENT_C,
    FOREIGN KEY (USER_NO) REFERENCES TB_COMMENT_C
);

----챌린지 첨부파일
DROP TABLE TB_ATTACHED_FILE_C;
CREATE TABLE TB_ATTACHED_FILE_C (
	FILE_NO	        NUMBER	        NOT NULL,
	POST_NO     	NUMBER	        NOT NULL,
	USER_NO	        NUMBER	        NOT NULL,
	FILE_NAME	    VARCHAR2(255)	DEFAULT '' NOT NULL,
	MFILE_NAME	    VARCHAR2(255)	DEFAULT '' NOT NULL,
    CONSTRAINT PK_TB_ATTACHED_FILE_C PRIMARY KEY(FILE_NO),
    CONSTRAINT FK_TB_ATTACHED_FILE_C FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);

DROP SEQUENCE SEQ_CHA_FNO;
CREATE SEQUENCE SEQ_CHA_FNO NOCYCLE NOCACHE;

----챌린지 리뷰
DROP TABLE TB_REVIEW_C;
CREATE TABLE TB_REVIEW_C(
    REVIEW_NO NUMBER	NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	REVIEW_NAME	VARCHAR2(30)		NOT NULL,
	REVIEW_CONTENT	VARCHAR2(4000)		NOT NULL,
    REVIEW_STAR NUMBER NOT NULL,
	BEG_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
    STAR NUMBER NOT NULL,
	THUMBNAIL	VARCHAR2(100),
	MOD_YN	CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	FMOD_DATE	TIMESTAMP   DEFAULT SYSDATE,
	DEL_YN	CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_REVIEW_C PRIMARY KEY(REVIEW_NO),
    CONSTRAINT FK_TB_REVIEW_C FOREIGN KEY(USER_NO) REFERENCES TB_USER(USER_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);

----챌린지 참여
DROP TABLE TB_PARTICIPATE_C;
CREATE TABLE TB_PARTICIPATE_C (
	PARTI_NO	NUMBER		NOT NULL,
	POST_NO	    NUMBER		NOT NULL,
	USER_NO	    NUMBER		NOT NULL,
	PARTI_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	STOP_YN	CHAR(1)	DEFAULT 'N' CHECK(STOP_YN IN('Y', 'N')),
    USER_NO2    NUMBER	    NOT NULL,
    CONSTRAINT PK_TB_PARTICIPATE_C PRIMARY KEY(PARTI_NO),
    CONSTRAINT FK_TB_PARTICIPATE_C FOREIGN KEY(POST_NO) REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);

ALTER TABLE TB_PARTICIPATE_C ADD CONSTRAINT FK_TB_USER_TO_TB_PARTICIPATE_C FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

DROP SEQUENCE SEQ_CHA_PARNO;
CREATE SEQUENCE SEQ_CHA_PARNO;

----챌린지 댓글 추천
DROP TABLE TB_RECOMMEND_COMMENT_C;
CREATE TABLE TB_RECOMMEND_COMMENT_C (
	RECOM_NO	NUMBER		NOT NULL,
	COMM_NO	    NUMBER		NOT NULL,
	POST_NO	    NUMBER		NOT NULL,
	USER_NO	    NUMBER		NOT NULL,
	RECOM_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	DEL_YN	CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    USER_NO2    NUMBER	    NOT NULL,
    CONSTRAINT PK_TB_RECOMMEND_COMMENT_C PRIMARY KEY(RECOM_NO),
    CONSTRAINT FK_TB_RECOMMEND_COMMENT_C FOREIGN KEY(COMM_NO)
    REFERENCES TB_COMMENT_C(COMM_NO),
    FOREIGN KEY (POST_NO) REFERENCES TB_COMMENT_C,
    FOREIGN KEY (USER_NO) REFERENCES TB_COMMENT_C
);

ALTER TABLE TB_RECOMMEND_COMMENT_C
ADD CONSTRAINT USER_NO2 FOREIGN KEY(USER_NO2) REFERENCES TB_USER(USER_NO);

DROP SEQUENCE SEQ_CHA_RCNO;
CREATE SEQUENCE SEQ_CHA_RCNO;

----챌린지 신고
DROP TABLE CHA_REPORT;
CREATE TABLE CHA_REPORT (
	REPORT_NO	NUMBER		NOT NULL,
	POST_NO	    NUMBER		NOT NULL,
	USER_NO	    NUMBER		NOT NULL,
	REPORT_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	COMM_NO	    NUMBER		NOT NULL,
	USER_NO2	NUMBER		NOT NULL,
    CONSTRAINT PK_CHA_REPORT PRIMARY KEY(REPORT_NO),
    CONSTRAINT FK_CHA_REPORT FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_CHALLENGE(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_CHALLENGE
);

ALTER TABLE CHA_REPORT ADD CONSTRAINT FK_TB_USER_TO_CHA_REPORT FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

ALTER TABLE CHA_REPORT ADD CONSTRAINT FK_TB_COMMENT_C_TO_CHA_REPORT FOREIGN KEY (COMM_NO)
REFERENCES TB_COMMENT_C (COMM_NO);

--새로운 챌린지 게시판 테이블에 데이터 넣어
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,1,'일주일 집밥 챌린지','일주일간 집밥 해먹기~ 집에서 밥먹기 아니구여 직접 해먹어야됩니다~ 배달ㄴㄴ',SYSDATE,SYSDATE+30,'100','50','/Recipetory/WebContent/img/challengeBoard/jipbab.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,2,'밀가루 끊기 챌린지','밀가루를 끊으면 피부개선, 다이어트, 소화불량 등에 효과가 있대요~',SYSDATE,SYSDATE+40,'90','30','/Recipetory/WebContent/img/challengeBoard/flour.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,3,'물 2L 마시기 챌린지','세계보건기구 WHO에서는 하루 약 2L 정도의 물을 섭위할 것을 권장하고 있습니다.',SYSDATE,SYSDATE+50,'80','20','/Recipetory/WebContent/img/challengeBoard/water.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,4,'아침먹기 챌린지','활발한 두뇌활동, 식사량 조절, 건강한 체중관리, 원할한 혈당조절을 원하신다면 아침을 먹어보아요~!',SYSDATE,SYSDATE+20,'70','10','/Recipetory/WebContent/img/challengeBoard/breakfast.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,5,'닭가슴살 챌린지','닭가슴살은 노화 방지, 간 기능 개선, 뇌 건강, 혈관이 꺠끗해지는 등 다양한 기능이 있대요. 레시피토리의 다양한 닭가슴살 레시피로 닭가슴살 챌린지에 도전해보아요~!',SYSDATE,SYSDATE+10,'60','5','/Recipetory/WebContent/img/challengeBoard/chickenbreast.jpg','N',NULL,'N');
COMMIT;

INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,1,'일주일 집밥 챌린지','일주일간 집밥 해먹기~ 집에서 밥먹기 아니구여 직접 해먹어야됩니다~ 배달ㄴㄴ',SYSDATE,SYSDATE+30,'100','50','/Recipetory/WebContent/img/challengeBoard/jipbab.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,2,'밀가루 끊기 챌린지','밀가루를 끊으면 피부개선, 다이어트, 소화불량 등에 효과가 있대요~',SYSDATE,SYSDATE+40,'90','30','/Recipetory/WebContent/img/challengeBoard/flour.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,3,'물 2L 마시기 챌린지','세계보건기구 WHO에서는 하루 약 2L 정도의 물을 섭위할 것을 권장하고 있습니다.',SYSDATE,SYSDATE+50,'80','20','/Recipetory/WebContent/img/challengeBoard/water.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,4,'아침먹기 챌린지','활발한 두뇌활동, 식사량 조절, 건강한 체중관리, 원할한 혈당조절을 원하신다면 아침을 먹어보아요~!',SYSDATE,SYSDATE+20,'70','10','/Recipetory/WebContent/img/challengeBoard/breakfast.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,5,'닭가슴살 챌린지','닭가슴살은 노화 방지, 간 기능 개선, 뇌 건강, 혈관이 꺠끗해지는 등 다양한 기능이 있대요. 레시피토리의 다양한 닭가슴살 레시피로 닭가슴살 챌린지에 도전해보아요~!',SYSDATE,SYSDATE+10,'60','5','/Recipetory/WebContent/img/challengeBoard/chickenbreast.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,6,'다이어트 식판 챌린지','다이어트 식판을 사용하면 음식 섞일 걱정도 없고 양 조절이 편하다고해요!',SYSDATE,SYSDATE+30,'100','50','/Recipetory/WebContent/img/challengeBoard/dietdish.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,7,'간헐적 단식 챌린지','간헐적 단식이 우리 몸의 생체시계를 변화시켜 제2형 당뇨병, 심혈관질환, 암 등의 치료에 도움이 되었다고 합니다.',SYSDATE,SYSDATE+40,'90','30','/Recipetory/WebContent/img/challengeBoard/shorteat.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,8,'포켓 샐러드 챌린지','다이어터 뿐만 아니라 몸을 만들기 위한 헬스케어 식단 등 여러가지 자신의 신체상황에 맞게 선택할수 있는 포켓샐러드!',SYSDATE,SYSDATE+50,'80','20','/Recipetory/WebContent/img/challengeBoard/pocketsalad.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,9,'블랙푸드 챌린지','블랙푸드란 검은색을 띤 자연식품 또는 이것으로 만든 음식입니다.',SYSDATE,SYSDATE+20,'70','10','/Recipetory/WebContent/img/challengeBoard/blackfood.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,10,'레드푸드 챌린지','빨간색을 띠는 식품을 통틀어 이르는 말로, 딸기, 사과, 석류, 토마토가 있습니다.',SYSDATE,SYSDATE+10,'60','5','/Recipetory/WebContent/img/challengeBoard/redfood.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,11,'퍼플푸드 챌린지','퍼플푸드란 시력과 고혈압에 좋은 청자색 식품을 말합니다.',SYSDATE,SYSDATE+30,'100','50','/Recipetory/WebContent/img/challengeBoard/purplefood.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,12,'그린푸드 챌린지','공해물질을 해독하고 세포 재생을 돕는 초록 채소, 과일과 야채의 초록색은 교감신경에 작용해 신장 간장의 기능을 활성화하고 공해물질을 해독시킵니다.',SYSDATE,SYSDATE+40,'90','30','/Recipetory/WebContent/img/challengeBoard/greenfood.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,13,'옐로우푸드 챌린지','노란색을 띠는 식품을 통틀어 이르는 말로, 호박, 바나나, 옥수수, 레몬 등을 말합니다.',SYSDATE,SYSDATE+50,'80','20','/Recipetory/WebContent/img/challengeBoard/yellowfood.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,14,'화이트푸드 챌린지','면역력을 강화시키는 흰색 식품으로, 베이지와 흰색 사이에 있는 배, 복숭아, 도라지, 콩나물, 무, 양파,마늘,버섯,인삼 등이 있다.',SYSDATE,SYSDATE+20,'70','10','/Recipetory/WebContent/img/challengeBoard/whitefood.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,15,'제로웨이스트 푸드 챌린지','환경 보호를 위해 음식물 쓰레기를 제로(0)에 가깝게 최소화하는 환경 운동에 참여해보아요',SYSDATE,SYSDATE+10,'60','5','/Recipetory/WebContent/img/challengeBoard/zerowaste.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,16,'금주 챌린지','금주를 하면 구강 및 몸의 염증이 개선되며, 두통도 완화된다고합니다.',SYSDATE,SYSDATE+30,'100','50','/Recipetory/WebContent/img/challengeBoard/noalcohol.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,17,'밀크어트 챌린지','우유를 활용한 다이어트로, 단백질을 보충하는 효과가 있고, 지방산 성분이 포만감을 주어 포식을 막아주는 효과가 있다.',SYSDATE,SYSDATE+40,'90','30','/Recipetory/WebContent/img/challengeBoard/milket.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,18,'6시 이후 금식 챌린지','6시 이후 금식은 소화기관의 부하를 줄여줍니다.',SYSDATE,SYSDATE+50,'80','20','/Recipetory/WebContent/img/challengeBoard/nodinner.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,19,'GI지수 낮음 음식 챌린지','GI지수가 낮은 음식은 저혈당지수 음식이라고도 하며, 고구마, 우유, 귀리, 호박 등이 있습니다.',SYSDATE,SYSDATE+20,'70','10','/Recipetory/WebContent/img/challengeBoard/lowgi.jpg','N',NULL,'N');
INSERT INTO TB_POST_C VALUES(SEQ_CHA_PTO.NEXTVAL,20,'일회용품 줄이기 챌린지','일회용품 사용을 줄이면 온실가스 배출량을 줄일수 있다고 합니다.',SYSDATE,SYSDATE+10,'60','5','/Recipetory/WebContent/img/challengeBoard/nodisposable.jpg','N',NULL,'N');
COMMIT;

---------끝.