DROP TABLE TB_USER;

-------------------------------회원 테이블 생성
CREATE TABLE TB_USER (
   USER_NO NUMBER NOT NULL,
   USER_ID VARCHAR2(30) NOT NULL,
   USER_PWD VARCHAR2(100) NOT NULL,
   USER_NICKNAME VARCHAR2(30) NOT NULL,
   UESR_EMAIL VARCHAR2(100) NOT NULL,
   USER_PHONE VARCHAR2(13) NOT NULL,
   USER_JOIN_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
   USER_TYPE VARCHAR2(20) NOT NULL,
   USER_DELETE_YN VARCHAR2(1) DEFAULT 'N' CHECK(USER_DELETE_YN IN('Y', 'N')), --CHECK("컬럼명" IN('Y' , 'N'))은 둘중 하나만 들어갈수 있다는 것.
   LASTLOGIN_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
   CONSTRAINT PK_TB_USER PRIMARY KEY(USER_NO)
)
;

--회원 코멘트 생성
COMMENT ON COLUMN TB_USER.USER_NO IS '회원 번호';
COMMENT ON COLUMN TB_USER.USER_ID IS '아이디';
COMMENT ON COLUMN TB_USER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN TB_USER.USER_NICKNAME IS '닉네임';
COMMENT ON COLUMN TB_USER.USER_EMAIL IS '이메일';
COMMENT ON COLUMN TB_USER.USER_PHONE IS '전화번호';
COMMENT ON COLUMN TB_USER.USER_JOIN_DATE IS '가입 일자';
COMMENT ON COLUMN TB_USER.USER_TYPE IS '회원 구분';
COMMENT ON COLUMN TB_USER.USER_DELETE_YN IS '탈퇴 여부';
COMMENT ON COLUMN TB_USER.LASTLOGIN_DATE IS '마지막 로그인 일자';

DROP SEQUENCE SEQ_UNO;
CREATE SEQUENCE SEQ_UNO; --회원번호 PK값 만들어주기 위한 시퀀스.(회원가입 하면서 번호 붙여지게)

INSERT INTO TB_USER ( --관리자 계정 추가. admin ssh
    USER_NO,
    USER_ID,
    USER_PWD,
    USER_NICKNAME,
    UESR_EMAIL,
    USER_PHONE,
    USER_JOIN_DATE,
    USER_TYPE,
    USER_DELETE_YN,
    LASTLOGIN_DATE
    ) VALUES(
    SEQ_UNO.NEXTVAL,
    'admin_ssh',
    'admin_ssh',
    '관리자 서성환',
    'thespeace1@gmail.com',
    '010-2015-9465',
    default,
    '관리자',
    default,
    default
    );
    
------------------------------------------매거진
--매거진 게시글 테이블 생성
DROP TABLE TB_BOARD_MAGAZINE;
CREATE TABLE TB_BOARD_MAGAZINE (
	POST_NO	        NUMBER                  NOT NULL,
	POST_NAME	    VARCHAR2(255)           NOT NULL,
	POST_CONTENT	VARCHAR2(4000)          NOT NULL,
	BEG_DATE	    TIMESTAMP DEFAULT SYSDATE	NOT NULL,
	HITS	        NUMBER  DEFAULT '0' 	NOT NULL,
	RECOM_NUM   	NUMBER	DEFAULT '0'     NOT NULL,
	SCRAP_NUM	    NUMBER	DEFAULT '0'     NOT NULL,
	COMM_NUM	    NUMBER	DEFAULT '0'     NOT NULL,
	REPORT_NUM	    NUMBER	DEFAULT '0'     NOT NULL,
	MOD_YN	        CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	FMOD_DATE   	TIMESTAMP DEFAULT SYSDATE NOT NULL,
	DEL_YN	        CHAR(1) DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
	USER_NO	        NUMBER	                NOT NULL,
    CONSTRAINT PK_TB_BOARD_MAGAZINE PRIMARY KEY(POST_NO)
)
;

--매거진 게시글 코멘트 생성
COMMENT ON COLUMN TB_BOARD_MAGAZINE.POST_NO IS '매거진 게시글 번호';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.POST_NAME IS '매거진명';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.POST_CONTENT IS '매거진 본문 내용';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.BEG_DATE IS '작성일';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.HITS IS '조회 수';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.RECOM_NUM IS '추천 수';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.SCRAP_NUM IS '스크랩 수';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.COMM_NUM IS '댓글 수';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.REPORT_NUM IS '신고 수';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.MOD_YN IS '수정 여부';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.FMOD_DATE IS '마지막 수정일자';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.DEL_YN IS '삭제 여부';
COMMENT ON COLUMN TB_BOARD_MAGAZINE.USER_NO IS '회원 번호';

DROP SEQUENCE SEQ_MAG_PNO;
CREATE SEQUENCE SEQ_MAG_PNO;

INSERT INTO TB_BOARD_MAGAZINED VALUES(SEQ_MAG_PNO.NEXTVAL, '우유자조금관리위원회, 연말 홈파티용 우유활용 레시피 추천','내용',
DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT);

-------------------------------------매거진 댓글
DELETE TALBE TB_COMMENT_M;
CREATE TABLE TB_COMMENT_M (
	COMM_NO	        NUMBER	NOT NULL,
	POST_NO	        NUMBER	NOT NULL,
	COMM_CONTENT	VARCHAR2(4000)	NOT NULL,
	COMM_ORDER	    NUMBER	NOT NULL,
	RECOM_NUM	    NUMBER	DEFAULT '0' NOT NULL,
	BEG_DATE	    TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MOD_DATE	    TIMESTAMP DEFAULT SYSDATE NOT NULL,
	REPORT_YN	    CHAR(1)	DEFAULT 'N' CHECK(REPORT_YN IN('Y', 'N')),
	MOD_YN	        CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	DEL_YN	        CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
	USER_NO	        NUMBER	NOT NULL,
    CONSTRAINT PK_TB_COMMENT_M PRIMARY KEY(COMM_NO),
    CONSTRAINT FK_TB_COMMENT_M FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_MAGAZINE(POST_NO)
);


-------------------------------------메거진 대댓글
CREATE TABLE TB_COMMENT_M2 (
	COMM_NO	NUMBER	NOT NULL,
	POST_NO	NUMBER	NOT NULL,
	COMM_CONTENT	VARCHAR2(4000)	NOT NULL,
	COMM_ORDER	NUMBER	NOT NULL,
	RECOM_NUM	NUMBER	DEFAULT '0' NOT NULL,
	BEG_DATE	TIMESTAMP   DEFAULT SYSDATE	NOT NULL,
	MOD_DATE	TIMESTAMP	DEFAULT SYSDATE NOT NULL,
	REPORT_YN	CHAR(1)	DEFAULT 'N' CHECK(REPORT_YN IN('Y', 'N')),
	MOD_YN	CHAR(1)	DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
	DEL_YN	CHAR(1)	DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
	USER_NO	NUMBER	NOT NULL,
    CONSTRAINT FK_TB_COMMENT_M2 FOREIGN KEY(POST_NO)
    REFERENCES TB_COMMENT_M(POST_NO)
);









