--메거진 데이터 생성
INSERT INTO TB_BOARD_MAGAZINE(
    POST_NO,USER_NO,POST_NAME,POST_CONTENT,BEG_DATE,
	HITS,RECOM_NUM,SCRAP_NUM,COMM_NUM,MOD_YN,FMOD_DATE,DEL_YN
)VALUES(
    SEQ_MAG_PNO.NEXTVAL,'1','맛있는 제목','맛있는 내용',default,default,default,default,
    default,default,default,default
    );
    
INSERT INTO TB_BOARD_MAGAZINE(
    POST_NO,POST_NAME,POST_CONTENT,BEG_DATE,
	HITS,RECOM_NUM,SCRAP_NUM,COMM_NUM,MOD_YN,FMOD_DATE,DEL_YN,ADMIN_NO
)VALUES(
    SEQ_MAG_PNO.NEXTVAL,'반갑네요','그러게요',default,default,default,default,
    default,default,default,DEFAULT,'1'
    );
    
    INSERT INTO TB_BOARD_MAGAZINE(
    POST_NO,POST_NAME,POST_CONTENT,BEG_DATE,
	HITS,RECOM_NUM,SCRAP_NUM,COMM_NUM,MOD_YN,FMOD_DATE,DEL_YN,ADMIN_NO
)VALUES(
    SEQ_MAG_PNO.NEXTVAL,'디비문제로','고생좀했네요 하',default,default,default,default,
    default,default,default,DEFAULT,'1'
    );

INSERT INTO TB_BOARD_MAGAZINE(
    POST_NO,POST_NAME,POST_CONTENT,BEG_DATE,
	HITS,RECOM_NUM,SCRAP_NUM,COMM_NUM,MOD_YN,FMOD_DATE,DEL_YN,ADMIN_NO
)VALUES(
    SEQ_MAG_PNO.NEXTVAL,'우리 조금만 더 ','힘냅시다',default,default,default,default,
    default,default,default,DEFAULT,'1'
    );

commit;

--메거진 댓글 생성
INSERT INTO TB_COMMENT_M(
    COMM_NO, POST_NO, USER_NO, COMM_CONTENT,
	COMM_ORDER, RECOM_NUM, BEG_DATE, MOD_DATE, MOD_YN, DEL_YN	
)VALUES(
    SEQ_MAG_CNO.NEXTVAL,'1','1','맛있는 댓글',
    SEQ_MAG_CNO_CNO.NEXTVAL,default,default,default,default,default
    );
    
COMMIT;

INSERT INTO TB_BOARD_MAGAZINE(
    POST_NO,POST_NAME,POST_CONTENT,BEG_DATE,
	HITS,RECOM_NUM,SCRAP_NUM,COMM_NUM,MOD_YN,FMOD_DATE,DEL_YN,ADMIN_NO
)VALUES(
    SEQ_MAG_PNO.NEXTVAL,'바바','리안',default,default,default,default,
    default,default,default,DEFAULT,1
    );
    
--SELECT * FROM TB_BOARD_MAGAZINE WHERE POST_NO = ?;
    

--메거진 게시판 컬럼 변경 (USER_NO -> ADMIN_NO)
ALTER TABLE TB_BOARD_MAGAZINE DROP COLUMN USER_NO;

ALTER TABLE TB_BOARD_MAGAZINE ADD(ADMIN_NO NUMBER); 

ALTER TABLE TB_BOARD_MAGAZINE ADD CONSTRAINT FK_TB_BOARD_MAGAZINE FOREIGN KEY (ADMIN_NO)
REFERENCES TB_ADMIN(ADMIN_NO);
