--레시피 게시글
DROP TABLE TB_BOARD_RECEIPT;
DROP TABLE TB_BOARD_RECIPE;
CREATE TABLE TB_BOARD_RECIPE2 (
   POST_NO       NUMBER      NOT NULL,
   USER_NO       NUMBER      NOT NULL,
   POST_NAME   VARCHAR2(30)      NOT NULL,
   BEG_DATE   TIMESTAMP   DEFAULT SYSDATE,
    INGREDIENT1 VARCHAR2(30)    NULL,
    INGREDIENT2 VARCHAR2(30)    NULL,
    INGREDIENT3 VARCHAR2(30)    NULL,
    INGREDIENT4 VARCHAR2(30)    NULL,
    INGREDIENT5 VARCHAR2(30)    NULL,
    POST_CONTENT1   VARCHAR2(4000)      NULL,
    POST_CONTENT2   VARCHAR2(4000)      NULL,
    POST_CONTENT3   VARCHAR2(4000)      NULL,
    POST_CONTENT4   VARCHAR2(4000)      NULL,
    POST_CONTENT5   VARCHAR2(4000)      NULL,
   THUMBNAIL   VARCHAR2(100),
   MOD_YN   CHAR(1)   DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
   DEL_YN   CHAR(1)   DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
   FMOD_DATE   TIMESTAMP,
    CONSTRAINT PK_TB_BOARD_RECIPE2 PRIMARY KEY(POST_NO),
    CONSTRAINT FK_TB_BOARD_RECIPE2 FOREIGN KEY(USER_NO)
    REFERENCES TB_USER(USER_NO)
);

DROP SEQUENCE SEQ_REC_RNO;
CREATE SEQUENCE SEQ_REC_RNO NOCYCLE NOCACHE;

--레시피 댓글
DROP TABLE TB_COMMNET_R;
CREATE TABLE TB_COMMNET_R (
   COMM_NO           NUMBER   NOT NULL,
   POST_NO           NUMBER   NOT NULL,
   USER_NO           NUMBER   NOT NULL,
   COMM_CONTENT   VARCHAR2(4000)   NOT NULL,
   COMM_ORDER       NUMBER   NOT NULL,
   RECOM_NUM       NUMBER   DEFAULT '0' NOT NULL,
   BEG_DATE       TIMESTAMP DEFAULT SYSDATE NOT NULL,
   MOD_DATE       TIMESTAMP DEFAULT SYSDATE NOT NULL,
   MOD_YN           CHAR(1)   DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
   DEL_YN           CHAR(1)   DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_COMMENT_R PRIMARY KEY(COMM_NO,POST_NO,USER_NO),
    CONSTRAINT FK_TB_COMMENT_R FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE2(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE2
);

DROP SEQUENCE SEQ_REC_CNO;
CREATE SEQUENCE SEQ_REC_CNO;

--레시피 대댓글
DROP TABLE TB_COMMENT_R2;

CREATE TABLE TB_COMMENT_R2 (
   COMM_NO         NUMBER NOT NULL,
    POST_NO         NUMBER NOT NULL,
    USER_NO         NUMBER NOT NULL,
   COMM_CONTENT   VARCHAR2(4000)   NOT NULL,
   COMM_ORDER       NUMBER       NOT NULL,
   RECOM_NUM       NUMBER       DEFAULT '0' NOT NULL,
   BEG_DATE       TIMESTAMP   DEFAULT SYSDATE   NOT NULL,
   MOD_DATE       TIMESTAMP   DEFAULT SYSDATE NOT NULL,
   MOD_YN           CHAR(1)       DEFAULT 'N' CHECK(MOD_YN IN('Y', 'N')),
   DEL_YN           CHAR(1)       DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N'))
);
ALTER TABLE TB_COMMENT_R2
ADD CONSTRAINT FK_COMMENT_R2
FOREIGN KEY (COMM_NO, POST_NO, USER_NO)
REFERENCES TB_COMMENT_R (COMM_NO, POST_NO, USER_NO);

--레시피 첨부파일
DROP TABLE TB_ATTACHED_FILE_R;

CREATE TABLE TB_ATTACHED_FILE_R (
   FILE_NO           NUMBER           NOT NULL,
   POST_NO        NUMBER           NOT NULL,
   USER_NO           NUMBER           NOT NULL,
   MFILE_NAME       VARCHAR2(255)   DEFAULT '' NOT NULL,
    CONSTRAINT PK_TB_ATTACHED_FILE_R PRIMARY KEY(FILE_NO),
    CONSTRAINT FK_TB_ATTACHED_FILE_R FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE2(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE2
);

DROP SEQUENCE SEQ_REC_FNO;
CREATE SEQUENCE SEQ_REC_FNO NOCYCLE NOCACHE;

--레시피 스크랩
DROP TABLE TB_SCRAP_R;
CREATE TABLE TB_SCRAP_R (
   SCRAP_NO       NUMBER       NOT NULL,
   USER_NO           NUMBER       NOT NULL,
   POST_NO           NUMBER       NOT NULL,
   USER_NO2        NUMBER       NOT NULL,
   SCARP_DATE       TIMESTAMP   DEFAULT SYSDATE NOT NULL,
   DEL_YN           CHAR(1)       DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
    CONSTRAINT PK_TB_SCRAP_R PRIMARY KEY(SCRAP_NO),
    CONSTRAINT FK_TB_SCRAP_R FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE2(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE2
);
ALTER TABLE TB_SCRAP_R ADD CONSTRAINT FK_TB_USER_TO_TB_SCRAP_R_1 FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

DROP SEQUENCE SEQ_REC_SNO;
CREATE SEQUENCE SEQ_REC_SNO;

--레시피 게시글 추천
DROP TABLE TB_RECOMMEND_R;

CREATE TABLE TB_RECOMMEND_R (
   RECOM_NO       NUMBER      NOT NULL,
   POST_NO           NUMBER      NOT NULL,
   USER_NO           NUMBER      NOT NULL,
   RECOM_DATE       TIMESTAMP   DEFAULT SYSDATE NOT NULL,
   DEL_YN           CHAR(1)       DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
   USER_NO2       NUMBER      NOT NULL,
    CONSTRAINT PK_TB_RECOMMEND_R PRIMARY KEY(RECOM_NO),
    CONSTRAINT FK_TB_RECOMMEND_R FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE2(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE2
);

ALTER TABLE TB_RECOMMEND_R ADD CONSTRAINT FK_TB_USER_TO_TB_RECOMMEND_R FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

DROP SEQUENCE SEQ_REC_RNO;
CREATE SEQUENCE SEQ_REC_RNO;

--레시피 댓글 추천
DROP TABLE TB_RECOMMEND_COMMENT_R;
CREATE TABLE TB_RECOMMEND_COMMENT_R (
   RECOM_NO   NUMBER      NOT NULL,
   COMM_NO       NUMBER      NOT NULL,
   POST_NO       NUMBER      NOT NULL,
   USER_NO       NUMBER      NOT NULL,
   RECOM_DATE   TIMESTAMP   DEFAULT SYSDATE NOT NULL,
   DEL_YN       CHAR(1)       DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')),
   USER_NO2   NUMBER      NOT NULL,
    CONSTRAINT PK_TB_RECOMMEND_COMMENT_R PRIMARY KEY(RECOM_NO)
    --CONSTRAINT FK_TB_RECOMMEND_COMMENT_R FOREIGN KEY(COMM_NO) --외래키 아직 못함 왜인지 안들어가
   -- REFERENCES TB_COMMENT_R(COMM_NO)
    --FOREIGN KEY (POST_NO) REFERENCES TB_COMMENT_R,
   -- FOREIGN KEY (USER_NO) REFERENCES TB_COMMENT_R
);

ALTER TABLE TB_RECOMMEND_COMMENT_R
ADD CONSTRAINT USER_NO2 FOREIGN KEY(USER_NO2) REFERENCES TB_USER(USER_NO);

--레시피 신고 관리
DROP TABLE REC_REPORT;

CREATE TABLE REC_REPORT (
   REPORT_NO   NUMBER      NOT NULL,
   POST_NO       NUMBER      NOT NULL,
   USER_NO       NUMBER      NOT NULL,
   REPORT_DATE   TIMESTAMP   DEFAULT SYSDATE   NOT NULL,
   COMM_NO       NUMBER      NOT NULL,
   USER_NO2   NUMBER      NOT NULL,
    CONSTRAINT PK_REC_REPORT PRIMARY KEY(REPORT_NO),
    CONSTRAINT FK_REC_REPORT FOREIGN KEY(POST_NO)
    REFERENCES TB_BOARD_RECIPE2(POST_NO),
    FOREIGN KEY (USER_NO) REFERENCES TB_BOARD_RECIPE2
);

ALTER TABLE REC_REPORT ADD CONSTRAINT FK_TB_USER_TO_REC_REPORT FOREIGN KEY (USER_NO2)
REFERENCES TB_USER (USER_NO);

--ALTER TABLE REC_REPORT ADD CONSTRAINT FK_TB_COMMENT_R_TO_REC_REPORT FOREIGN KEY (COMM_NO) 제약조건이 안걸림 내가보니 COMM_NO 이녀석이 문제다.
--REFERENCES TB_COMMENT_R (COMM_NO);



COMMIT;