//회원테이블 생성
CREATE TABLE TB_USER (
   USER_NO NUMBER NOT NULL,
   USER_ID VARCHAR2(30) NOT NULL,
   USER_PWD VARCHAR2(100) NOT NULL,
   USER_NICKNAME VARCHAR2(30) NOT NULL,
   USER_EMAIL VARCHAR2(100) NOT NULL,
   USER_PHONE VARCHAR2(13) NOT NULL,
   USER_JOIN_DATE TIMESTAMP DEFAULT SYSDATE,
   USER_TYPE VARCHAR2(20) NOT NULL,
   USER_DELETE_YN CHAR(1)  DEFAULT ‘N’  NOT NULL,
   LASTLOGIN_DATE TIMESTAMP DEFAULT SYSDATE,
   CONSTRAINT PK_TB_USER PRIMARY KEY(USER_NO)
);

//회원번호PK값 만들어주기위한 시퀀스
CREATE SEQUENCE SEQ_UNO;

//회원테이블에 값 입력
INSERT INTO TB_USER(
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'red',  '111',  '빨강이', 'red@gmail.com', '010-1111-1111', DEFAULT,  '기본', DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'orange',  '222',  '주황이', 'orange@gmail.com', '010-2222-2222',  DEFAULT,  '기본', DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'yellow',  '333',  '노랑이', 'yellow@gmail.com', '010-3333-3333', DEFAULT,  '기본', DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'green',  '444',  '초록이', 'green@gmail.com', '010-4444-4444', DEFAULT,  '기본', DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'blue',  '555',  '파랑이', 'blue@gmail.com', '010-5555-5555', DEFAULT,  '기본', DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'navy',  '666',  '남이', 'navy@gmail.com', '010-6666-6666', DEFAULT,  '기본', DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'purple',  '777',  '보라', 'purple@gmail.com', '010-7777-7777', DEFAULT,  '기본', DEFAULT, DEFAULT );

	
---------------------------------------------------------
	
// 관리자 테이블 생성
CREATE TABLE TB_ADMIN (
   ADMIN_NO   NUMBER   NOT NULL,
   ADMIN_ID   VARCHAR2(30)   NOT NULL,
   ADMIN_PWD   VARCHAR2(100)   NOT NULL,
   ADMIN_NAME   VARCHAR2(30)   NOT NULL,
   ADMIN_LV   VARCHAR2(30)  DEFAULT 'Lv1'  NOT NULL,
   JOIN_DATE   TIMESTAMP DEFAULT SYSDATE,
   CONSTRAINT PK_TB_ADMIN PRIMARY KEY(ADMIN_NO)
);


CREATE SEQUENCE SEQ_ADMIN;

// 관리자 테이블에 값 입력
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin1',  'aaa',  '강동원', DEFAULT, DEFAULT );
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin2',  'bbb',  '이지은', 'Lv3', DEFAULT );
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin3',  'ccc',  '최우식', 'Lv2', DEFAULT );
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin4',  'ddd',  '제임스', 'Lv2', DEFAULT );
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin5',  'eee',  '찰스', DEFAULT, DEFAULT );

