--회원테이블 생성
CREATE TABLE TB_USER (
   USER_NO NUMBER NOT NULL,
   USER_ID VARCHAR2(30) NOT NULL,
   USER_PWD VARCHAR2(100) NOT NULL,
   USER_NICKNAME VARCHAR2(30) NOT NULL,
   USER_EMAIL VARCHAR2(100) NOT NULL,
   USER_PHONE VARCHAR2(13) NOT NULL,
   USER_JOIN_DATE TIMESTAMP DEFAULT SYSDATE,
   USER_TYPE VARCHAR2(20) NOT NULL,
   USER_DELETE_YN CHAR(1)  DEFAULT ‘N’  NOT NULL,
   LASTLOGIN_DATE TIMESTAMP DEFAULT SYSDATE,
   CONSTRAINT CHK_USER_DELETE_YN CHECK (USER_DELETE_YN IN ('Y','N')),
   CONSTRAINT PK_TB_USER PRIMARY KEY(USER_NO)
);


--회원번호PK값 만들어주기위한 시퀀스
CREATE SEQUENCE SEQ_UNO;

--회원테이블에 값 입력
INSERT INTO TB_USER(
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'red',  '111',  '빨강이', 'red@gmail.com', '010-1111-1111', DEFAULT,  '기본', DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'orange',  '222',  '주황이', 'orange@gmail.com', '010-2222-2222',  DEFAULT,  '기본', DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'yellow',  '333',  '노랑이', 'yellow@gmail.com', '010-3333-3333', DEFAULT,  '기본', DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'green',  '444',  '초록이', 'green@gmail.com', '010-4444-4444', DEFAULT,  '기본', DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'blue',  '555',  '파랑이', 'blue@gmail.com', '010-5555-5555', DEFAULT,  '기본', DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'navy',  '666',  '남이', 'navy@gmail.com', '010-6666-6666', DEFAULT,  '기본', DEFAULT, DEFAULT );
INSERT INTO TB_USER (
	USER_NO, USER_ID,  USER_PWD, USER_NICKNAME, USER_EMAIL, USER_PHONE, USER_JOIN_DATE, USER_TYPE, USER_DELETE_YN, LASTLOGIN_DATE
	) VALUES (
	SEQ_UNO.NEXTVAL, 'purple',  '777',  '보라', 'purple@gmail.com', '010-7777-7777', DEFAULT,  '기본', DEFAULT, DEFAULT );

	
-----------------------------------------------------------------------
	
--관리자 테이블 생성
CREATE TABLE TB_ADMIN (
   ADMIN_NO NUMBER NOT NULL,
   ADMIN_ID VARCHAR2(30) NOT NULL,
   ADMIN_PWD VARCHAR2(100) NOT NULL,
   ADMIN_NAME VARCHAR2(30) NOT NULL,
   ADMIN_LV VARCHAR2(30) DEFAULT 'Lv1' NOT NULL,
   JOIN_DATE TIMESTAMP DEFAULT SYSDATE,
   CONSTRAINT PK_TB_ADMIN PRIMARY KEY(ADMIN_NO)
);


CREATE SEQUENCE SEQ_ADMIN;

--관리자 테이블에 값 입력
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin1',  'aaa',  '강동원', DEFAULT, DEFAULT );
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin2',  'bbb',  '이지은', 'Lv3', DEFAULT );
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin3',  'ccc',  '최우식', 'Lv2', DEFAULT );
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin4',  'ddd',  '제임스', 'Lv2', DEFAULT );
INSERT INTO TB_ADMIN (
	ADMIN_NO, ADMIN_ID,  ADMIN_PWD, ADMIN_NAME, ADMIN_LV, JOIN_DATE
	) VALUES (
	SEQ_ADMIN.NEXTVAL, 'admin5',  'eee',  '찰스', DEFAULT, DEFAULT );

---------------------------------------------------------------------
--공지사항 테이블 생성
CREATE TABLE TB_NOTICE (
   NOTICE_NO NUMBER NOT NULL,
   NOTICE_TITLE VARCHAR2(255) NOT NULL,
   NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
   ADMIN_NO NUMBER,
   CREATE_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
   VIEW_COUNT NUMBER DEFAULT '0' NOT NULL,
   MOD_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(MOD_YN IN('Y', 'N')),
   MOD_DATE  TIMESTAMP DEFAULT SYSDATE,
   DELETE_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(DELETE_YN IN('Y', 'N')),
   CONSTRAINT PK_TB_NOTICE PRIMARY KEY(NOTICE_NO),
   CONSTRAINT FK_ADMIN_NO FOREIGN KEY (ADMIN_NO) REFERENCES TB_ADMIN(ADMIN_NO) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_NOTICE;

--공지사항에 값 입력
INSERT INTO TB_NOTICE (
	NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, VIEW_COUNT, MOD_YN, MOD_DATE, DELETE_YN
	) VALUES (
	SEQ_NOTICE.NEXTVAL, '레시피토리 오픈 안내',  '공지사항 내용', '1', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
	NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, VIEW_COUNT,  MOD_YN, MOD_DATE, DELETE_YN
	) VALUES (
	SEQ_NOTICE.NEXTVAL, '서비스 이용약관 개정 안내',  '공지사항 내용', '2', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
	NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, VIEW_COUNT,  MOD_YN, MOD_DATE, DELETE_YN
	) VALUES (
	SEQ_NOTICE.NEXTVAL, '서비스 개편 및 이용안내',  '공지사항 내용', '3', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
	NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, VIEW_COUNT,  MOD_YN, MOD_DATE, DELETE_YN
	) VALUES (
	SEQ_NOTICE.NEXTVAL, '업그레이드 안내 공지',  '공지사항 내용', '4', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_NOTICE (
	NOTICE_NO, NOTICE_TITLE,  NOTICE_CONTENT, ADMIN_NO, CREATE_DATE, VIEW_COUNT,  MOD_YN, MOD_DATE, DELETE_YN
	) VALUES (
	SEQ_NOTICE.NEXTVAL, '12/22 서비스 점검안내',  '공지사항 내용', '5', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

--------------------------------------------------------------------------------

--문의사항 테이블 생성
CREATE TABLE TB_QNA (
   QNA_NO NUMBER NOT NULL,
   QNA_TITLE VARCHAR2(255) NOT NULL,
   QNA_CONTENT VARCHAR2(4000) NOT NULL,
   USER_NO NUMBER,
   CREATE_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
   VIEW_COUNT NUMBER DEFAULT '0' NOT NULL,
   ANSWER VARCHAR2(4000),
   MOD_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(MOD_YN IN('Y', 'N')),
   MOD_DATE  TIMESTAMP DEFAULT SYSDATE,
   STATUS_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(STATUS_YN IN('Y', 'N')),
   DELETE_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(DELETE_YN IN('Y', 'N')),
   CONSTRAINT PK_TB_QNA PRIMARY KEY(QNA_NO),
   CONSTRAINT FK_QNA FOREIGN KEY (USER_NO) REFERENCES TB_USER(USER_NO) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_QNA;


--문의사항 테이블에 값 입력
INSERT INTO TB_QNA (
	QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, CREATE_DATE, VIEW_COUNT, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_QNA.NEXTVAL, '회원가입 문의',  '문의사항 내용', '5', DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_QNA (
	QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, CREATE_DATE, VIEW_COUNT, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_QNA.NEXTVAL, '레시피 올리는 방법',  '문의사항 내용', '4', DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_QNA (
	QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, CREATE_DATE, VIEW_COUNT, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_QNA.NEXTVAL, '비밀번호 변경',  '문의사항 내용', '3', DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_QNA (
	QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, CREATE_DATE, VIEW_COUNT, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_QNA.NEXTVAL, '레시피 수정',  '문의사항 내용', '2', DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_QNA (
	QNA_NO, QNA_TITLE, QNA_CONTENT, USER_NO, CREATE_DATE, VIEW_COUNT, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_QNA.NEXTVAL,'동영상 첨부 방법 문의',  '문의사항 내용', '1', DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);

--------------------------------------------------------------------------------

--신고 테이블 생성
CREATE TABLE TB_REPORT (
   REPORT_NO NUMBER NOT NULL,
   REPORT_TITLE VARCHAR2(255) NOT NULL,
   REPORT_CONTENT VARCHAR2(4000) NOT NULL,
   USER_NO NUMBER,
   CREATE_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
   VIEW_COUNT NUMBER DEFAULT '0' NOT NULL,
   ANSWER VARCHAR2(4000),
   MOD_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(MOD_YN IN('Y', 'N')),
   MOD_DATE  TIMESTAMP DEFAULT SYSDATE,
   STATUS_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(STATUS_YN IN('Y', 'N')),
   DELETE_YN CHAR(1) DEFAULT 'N' NOT NULL CHECK(DELETE_YN IN('Y', 'N')),
   CONSTRAINT PK_TB_REPORT PRIMARY KEY(REPORT_NO),
   CONSTRAINT FK_TB_REPORT FOREIGN KEY (USER_NO) REFERENCES TB_USER(USER_NO) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_REPORT;

--신고 테이블에 값 입력
INSERT INTO TB_REPORT (
	REPORT_NO, REPORT_TITLE, REPORT_CONTENT, USER_NO, CREATE_DATE, VIEW_COUNT, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_REPORT.NEXTVAL,'게시글 신고',  '신고 내용', '1', DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_REPORT (
	REPORT_NO, REPORT_TITLE, REPORT_CONTENT, USER_NO, CREATE_DATE, VIEW_COUNT, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_REPORT.NEXTVAL,'회원 신고',  '신고 내용', '3', DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_REPORT (
	REPORT_NO, REPORT_TITLE, REPORT_CONTENT, USER_NO, CREATE_DATE, VIEW_COUNT, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_REPORT.NEXTVAL,'댓글 신고',  '신고 내용', '5', DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_REPORT (
	REPORT_NO, REPORT_TITLE, REPORT_CONTENT, USER_NO, CREATE_DATE, VIEW_COUNT, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_REPORT.NEXTVAL,'적절하지 못한 게시글',  '신고 내용', '6', DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO TB_REPORT (
	REPORT_NO, REPORT_TITLE, REPORT_CONTENT, USER_NO, CREATE_DATE, VIEW_COUNT, ANSWER, MOD_YN, MOD_DATE, STATUS_YN, DELETE_YN
	) VALUES (
	SEQ_REPORT.NEXTVAL,'비방 댓글 신고',  '신고 내용', '7', DEFAULT, DEFAULT,'답변내용',DEFAULT, DEFAULT, DEFAULT, DEFAULT);



